### ISSUE TITLE
Cloud: Adjustments on screens (layout)

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#1]
As discussed, make sure that screens have the same look and feel, we've seen the following screens:

Taxes
Facilities
Branches
Inventory Group
UOM

1. Make sure that mandatory fields have the (*) in front so that the user knows that is mandatory
2. Remove word Flag from Active, keep Active check box as the first field on the insert / edit popup box
3. Some of the screens have field label uppercase, they should have only the first letter capitalized.
4. Popup dimensions should also be as standard (same) as possible.

**Comment by d3sqa** [comment]
Work in progress

**Comment by giovanicani** [comment]
please provide updated status

**Comment by d3sqa** [comment]
1. Mandatory fields have (*) in front of it
2. Active check box will be as the first field
3. Only first letter will be capitalized in screens
4. Popup dimensions are same

These points are done in the following screens;
Facilities
Branches
Inventory Group
UOM

Work is in progress on following screens;
Taxes
Unit Type
VMRS Codes
Surcharge
Shop Supply
Kit Detail

**Comment by d3sqa** [comment]
All above points have been done. Ready for testing in development environment.

**Comment by giovanicani** [comment]
please make sure you keep this on the STD Document. Will close the ticket.
