### ISSUE TITLE
Cloud: Part Screen - Attachments

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#10]
- Have an column to indicate if the file is the default image for the part (only one is allowed)
- Allow user to update image without having to close the screen. Every line should have an upload button
- Allow user to download / view image or document associated to that part.

![image](https://cloud.githubusercontent.com/assets/5666297/12203131/5473b5ee-b5fb-11e5-9fe4-e19246d99374.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by giovanicani** [comment]
What is the updated status ? Attachment screen still not working. 

- Attachment: Delete button not standard
- Attachment: Preview overrides current screen.
- When on detail screen, previewing image, press ESC, it goes back to Parts Listing, it should go back to the detailed tab.

**Comment by d3sqa** [comment]
@giovanicani API work is done for images now its integration is in progress.

**Comment by giovanicani** [comment]
still need further work.

**Comment by giovanicani** [comment]
please provide update.

**Comment by d3sqa** [comment]
@giovanicani Download/ view image or document associated to specific part has been done. 
Work in progress on handling special characters in description of attachments.

**Comment by giovanicani** [comment]
kindly provide brief update. Thanks!

**Comment by d3sqa** [comment]
Download/ view image or document associated to specific part has been done. 
Ready for testing at development environment.

**Comment by giovanicani** [comment]
skylook down. not able to test.

**Comment by giovanicani** [comment]
Although this screen may be working, I still find it a big confusing for the user, please do the following adjustments:


- If a file has been already uploaded, remove or disable the choose file button, and remove the "No File Chosen" verbiage. Just show the icon of the file type. User cannot change, need to delete and upload new file if want to change anything.
- If no file is yet uploaded, remove the question mark icon, just leave the button and the no file chosen verbiage.
- Remove the upload button on the action, as soon as a part is selected, it should be uploaded, or alternatively, when SAVE button is pressed then upload image.
- Remove Action column label
- Change Default column label to Main Image (only images can be checked as default), perhaps disable check boxes from non images file ?

![image](https://cloud.githubusercontent.com/assets/5666297/13325684/db9ab538-dbb0-11e5-8cdb-8ac1009be27f.png)

Getting error below when trying to upload.
![image](https://cloud.githubusercontent.com/assets/5666297/13325838/8972c178-dbb1-11e5-8be6-bd04d1885cae.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Above mentioned attachment's adjustments have been done. 
'Undefined error' could not be replicated by us. 
Ready for testing at development environment.

**Comment by giovanicani** [comment]
have you tested from outside the network ? using the skylook URL ?

**Comment by d3sqa** [comment]
@giovanicani Yes, we have tested it on skylook URL as well.
We are still trying to replicate its scenario.

**Comment by giovanicani** [comment]
still have the upload doc / image issue, as per meeting on Tuesday.

**Comment by giovanicani** [comment]
works.
