### ISSUE TITLE
Cloud: Safety Certificate Quick search does not work.

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#100]
If not work, please remove the field, just leave apply filter which is working.

![image](https://cloud.githubusercontent.com/assets/5666297/14819416/15baea8a-0b90-11e6-9353-ef9e560cb7f6.png)

**Comment by d3sqa** [comment]
The Quick Search field has been disabled now.

![image](https://cloud.githubusercontent.com/assets/13255706/14843014/32777cb6-0c66-11e6-9fd0-920c9e3c4830.png)

**Comment by giovanicani** [comment]
please remove the quick search if it doesnt do anything.

Leaving it there will confuse users. thanks.

**Comment by d3sqa** [comment]
The Quick Search has been removed. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/14882518/af0a6b8e-0d52-11e6-80c3-5381ef8de04f.png)

**Comment by giovanicani** [comment]
okay
