### ISSUE TITLE
Cloud: Reading Reset Feature

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#101]
This is associated to ticket #89 

User to be able to reset Readings.

![image](https://cloud.githubusercontent.com/assets/5666297/14823748/a23e09cc-0ba1-11e6-8b9c-1b8424975d10.png)

Notes: 
- Reset fields only accessible if reset box is checked.
- Voided readings should be disconsidered when doing the validation
- User cannot un-void a reading
- User cannot update a reset reading. Only update allowed is to void.

**Comment by d3sqa** [comment]
Update:

Screen design has been completed. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/14916519/80f4b132-0e33-11e6-9048-9b59e96e42d6.png)

Working on the functionality

**Comment by d3ssupport** [comment]
done, testing in progress

**Comment by d3sqa** [comment]
@Giovani, should the reset at value be given 1st priority ? Please consider the following scenario:

- The user enters a value in Reset To field which starts to reflects in the existing reading field as well
- Now the user edits the existing value to some other value (lets say more than reset)
- Then Saves
- Currently, the readings given at the existing field (first column) gets the priority which makes the Reset At useless

Please provide your feedback on this

We are almost done. Doing some tweaks

**Comment by giovanicani** [comment]
Good question... if first column different than reset to (because the user changed the value on first column), when saving show message: 

Reading cannot be different than Reset To.

This message off course will only show up if the reset check box is checked.

**Comment by d3sqa** [comment]
Readings screen has been done and ready to test in development environment.

Following points have been done:

- Reset fields only accessible if reset box is checked.
- Voided readings should be disconsidered when doing the validation
- User cannot un-void a reading
- User cannot update a reset reading. Only update allowed is to void
- 'Reading cannot be different than Reset To' validation has also been applied

**Comment by giovanicani** [comment]
Used: Trailer # 354029, Reefer ER3065

Found several issues with this screen:

1. Editing Readings is very awkward. Type 100000, then try to fix to 130000 cursor goes back to the end of the number, and if not carefull, number becomes 100003. Please format the number after user left the field, and not while he is typing.

2. Buttons disabled after entering reefer hours? Why? Requirement is at least one of the 3 readings to be entered, which did happen as per below, why cannot save ?
![image](https://cloud.githubusercontent.com/assets/5666297/15118131/e082ddde-15d8-11e6-8fb4-6cd88d461049.png)

3. Selected KM, then entered reading, after tab out, the drop down box showed UOM back instead of keeping KM. See below... for some reason Reset At became KM. Reset At should not be changed if check box was not checked.
 
![image](https://cloud.githubusercontent.com/assets/5666297/15117907/c44f51ca-15d7-11e6-9ea5-be8c9b84d079.png)

4. Why RESET check boxes are disabled ?

**Comment by d3sqa** [comment]
Point # 1 has been done. Work in progress on other points

**Comment by giovanicani** [comment]
Make Hubo UOM = KM as default.

**Comment by d3sqa** [comment]
Above mentioned issues have been fixed
Hubo UOM would be by default KM now
Reset At flag should be enabled. Once checked, Reset At would be enabled and would be populated with existing value if exists any

Ready to test in development environment

**Comment by giovanicani** [comment]
great job. it works! thanks!
