### ISSUE TITLE
Cloud: Getting page unresponsive message from browser.

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#102]
This is when I use the RDP session given to me.

![image](https://cloud.githubusercontent.com/assets/5666297/14864696/07f2412e-0c89-11e6-9d00-0e2dcf0f49d6.png)

**Comment by giovanicani** [comment]
it eventually goes through... but veeery slow.

**Comment by giovanicani** [comment]
@tufailzafar Tufail to check connectivity and get back to Giovani

**Comment by giovanicani** [comment]
Admin is a bit quicker now, but inventory is very slow.... please provide update.

**Comment by d3ssupport** [comment]
issue resolved and ready for testing in Dev

**Comment by giovanicani** [comment]
works thanks!
