### ISSUE TITLE
Cloud: PO - How to handle re-ordering when items are on Back Order ?

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#103]

**Comment by giovanicani** [comment]
On the re-order report, when there are back order for a given part that is being re-ordered, it should add a note to the report saying:

Reorder Note: This part has a back order of 10 on the following PO(s): PO000123, PO000133, etc...

The reorder process will always be based on the actual current ONHAND for that part for that inventory.

It will be up to the user to follow up on those Back Order and cancel them or leave them open as required.

**Comment by d3sqa** [comment]
Back order quantity has been displayed on the report generated via min/max. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/15384670/c385b2c6-1db5-11e6-8928-95c8905a2edf.png)

Below is the screenshot of report created via usage:

![image](https://cloud.githubusercontent.com/assets/13255706/15384694/e78ec662-1db5-11e6-995b-4b7083a85e45.png)

We are picking up back orders against the POs whose Finalized Date and Void Date is NULL

Ready to test in development environment

**Comment by giovanicani** [comment]
okay.
