### ISSUE TITLE
MRO Link: Please allow more than one labour line with same description

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#105]
Associated to #93 

Please allow user to select the same labour line twice. Remove the unique validation

This is required because user cannot change SRT labour line description.

**Comment by d3ssupport** [comment]
If we allow user to add more than one Labour with same description data inconsistency may occur due to auto hold. we use labour description for comparison with the server.

It is suggested to  add a number as description postfix , see examples below 
i.e. LAB1:  A CHECK - B TRAIN CANPAR
     LAB2:  A CHECK - B TRAIN CANPAR_1
     LAB3:  A CHECK - B TRAIN CANPAR_2

please advise

**Comment by giovanicani** [comment]
As discussed, when selecting labour if there are another labour with same description on mobile, user needs to enter something on the notes to make it the overall DESCRIPTION + NOTES unique.

When doing the comparison on the server please use the DESCRIPTION + NOTES combination, since it should be unique.

**Comment by tufailzafar** [comment]
work in progress

**Comment by d3ssupport** [comment]
done, testing in progress

**Comment by d3ssupport** [comment]
Verified ready for testing in UAT

**Comment by giovanicani** [comment]
Thanks for the update.... it works...

Kindly change the message to say:

**A labour line with the same description has already been entered. Please enter further details into the notes field and press OK.**

![image](https://cloud.githubusercontent.com/assets/5666297/15015679/4e00a0a0-11db-11e6-8c6f-e95d0aa75dca.png)

**Comment by d3ssupport** [comment]
Message has been changed. Ready for Test in UAT.

**Comment by giovanicani** [comment]
thanks will do.

**Comment by d3sqa** [comment]
Message has been revised. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/15037363/cd45b80e-12b3-11e6-920c-fe6b50f46942.png)

Ready to test in UAT Environment

**Comment by giovanicani** [comment]
okay.
