### ISSUE TITLE
MRO Link: Cloud Layout Issues

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#106]
- Part code, description alignment improvements required
- \N appearing instead of new line
- Part Actual and Charge are missing. Actual should be zero and charge what the user has selected
- On labour change heading from Actual to Actual (T/S)
- Change %Margin to %Margin(Chg / Act).
- On labour Actual will always be ZERO as we are not using Timesheet yet.

![screen shot 2016-05-02 at 1 58 19 am](https://cloud.githubusercontent.com/assets/5666297/14949051/a6c8679a-1014-11e6-9286-f334bc0f1cb2.png)

**Comment by d3ssupport** [comment]
work in progress

**Comment by d3ssupport** [comment]
On labour Actual will always be ZERO as we are not using Timesheet yet.

* Question *: if actual becomes zero that would affect the margin formula on margin calculator as below
$MARGINCHR =   (($CHG_TOTAL- $ACT_TOTAL)/$CHG_TOTAL)*100

please advise

**Comment by giovanicani** [comment]
Margin will always be ZERO for now... until we can implement the timesheet feature.

**Comment by d3sqa** [comment]
@giovanicani, regarding the formula, the markup in this case will always be 100 and not 0. Please see example below:

![image](https://cloud.githubusercontent.com/assets/13255706/15040319/3958ec46-12cd-11e6-8ba0-b4135c793ba8.png)

Here, Charge is 0.75 and Actual is 0. Putting these in the formula:

Margin = ((0.75 - 0)/0.75) * 100     => 100

The value in actual will be 0 until the timesheet is incorporated.

Following points are also done:

- Parts grid alignment has been corrected

![image](https://cloud.githubusercontent.com/assets/13255706/15041438/605d84c0-12d5-11e6-8901-d51f8f9a6026.png)

- \N issue has been resolved

![image](https://cloud.githubusercontent.com/assets/13255706/15042011/c9ac3224-12d9-11e6-959a-a5f22fe5ecfe.png)

- Part actual will remain 0 and charge will be populated with part's QTY

- Header has been renamed to Actual (T/S) and margin label to %Margin(Chg / Act)

![image](https://cloud.githubusercontent.com/assets/13255706/15040406/030c490c-12ce-11e6-8db6-bfdfc6017e4f.png)

![image](https://cloud.githubusercontent.com/assets/13255706/15040413/08c61ac6-12ce-11e6-9998-0a045b701abf.png)

Ready to test in UAT Environment

**Comment by giovanicani** [comment]
((Labour Charge / Labour Actual) - 1 ) * 100 = % Margin, labour not known until we implement the TS, so please to avoid division by ZERO, make the % Margin always zero.

**Comment by d3sqa** [comment]
The formula has been incorporated.
Also, the font size has been reduced. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/15044265/ed032f9e-12ec-11e6-98eb-d479e38f25d4.png)

**Comment by giovanicani** [comment]
awesome thanks team.
