### ISSUE TITLE
MRO Link - Enable MRO Validation SRT / no SRT based on mobile user

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#107]
As discussed this morning, please add a field on the ym_users and ym_users_wv view that is called:

allow_srt_nosrt_same_ro_flag VARCHAR2(1) NOT NULL, values Y and N... default Y.

On Mobile...

Everytime user logs in, it will check this value on the server. 

**If value = 'Y', then...**
- Hide Create RO Link Button
- Bypass validation, and allow user to create SRT and no SRT labour lines on the same RO (as is today in PROD)

**If value = 'N', then...**
- Show Create RO Link Button (as is today on UAT)
- Validate that user wont be able to create SRT and no SRT labour lines on the same RO (as is today in UAT).

**Comment by d3ssupport** [comment]
done, testing in progress in UAT

**Comment by giovanicani** [comment]
Thanks Guys for the update.

**Comment by giovanicani** [comment]
works well on my tests. Require input from D3S.

**Comment by d3sqa** [comment]
Above feature has been incorporated in UAT. Ready to test

**Comment by giovanicani** [comment]
works.
