### ISSUE TITLE
MRO Link: License Plate not populated when NO BARCODE is selected

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#108]
See below, just started RO and License Plate is blank, it should have been A3, which was entered on the previous screen.

![image](https://cloud.githubusercontent.com/assets/5666297/15019427/fdfe3688-11eb-11e6-9afe-1c2bdf357578.png)

After creating Linked RO, LP is also blank. Note that the customer is blank as well.

![image](https://cloud.githubusercontent.com/assets/5666297/15019458/221f548e-11ec-11e6-911f-7623e0c29c66.png)

Please have this fixed. Thanks!

Please perform your test with and without reefer, with and without barcode.

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Issue has been fixed

Please see screenshots below:

Parent's RO Header:

![image](https://cloud.githubusercontent.com/assets/13255706/15038735/d8caabb0-12bf-11e6-8253-88c8e50acef0.png)

Linked RO Header:

![image](https://cloud.githubusercontent.com/assets/13255706/15038727/c223ad4e-12bf-11e6-91af-69ea294ef4f7.png)

Inquiry:

![image](https://cloud.githubusercontent.com/assets/13255706/15038747/f04c9636-12bf-11e6-90aa-8d7eccd65878.png)

With Reefer:

Parent RO:

![image](https://cloud.githubusercontent.com/assets/13255706/15038767/2d505b4e-12c0-11e6-91ac-a6342bfbf627.png)

Linked RO:

![image](https://cloud.githubusercontent.com/assets/13255706/15038784/49263758-12c0-11e6-814f-0e5170edaf4d.png)

![image](https://cloud.githubusercontent.com/assets/13255706/15038785/4e796342-12c0-11e6-9413-7c088c94250b.png)

New application updates are available at UAT. Ready to test

**Comment by giovanicani** [comment]
okay.
