### ISSUE TITLE
Cloud: RO Detail Screen Add Charge flag check box for Parts and Labour

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#109]
Add check box after labour & parts called charge. This field needs to be added on the labour and parts table (rep_work_order_labour(_wv), rep_work_order_parts(_wv) name it charge_flag default flagged)

**Comment by d3sqa** [comment]
New field has been added to both the tables. Work in progress on adding the check box in the labours and parts grid at RO Detail screen

**Comment by d3sqa** [comment]
Charge Flag has been added to both parts and labour and are checked by default. They can be unchecked at Complete and Action Required status

![12newwww](https://cloud.githubusercontent.com/assets/13255706/15268486/b67f67ee-19f9-11e6-923e-480ba75cf87f.png)

**Comment by giovanicani** [comment]
Thanks. What is the condition that an RO would go to action required?

**Comment by giovanicani** [comment]
Change label "Charge Flag" to "Chg Cust."

**Comment by d3sqa** [comment]
Label Charge Flag has been renamed to 'Chg Cust' at both Labour and Parts grid
Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/15312829/85ec4d08-1c20-11e6-9e95-1f9d32feedda.png)

Ready to test in development environment

**Comment by d3sqa** [comment]
@giovanicani, the RO would go into ACTION REQUIRED status whenever upon completion from mobile, there is an ERROR from EMDECS.
This feature would be changed soon as we won't be sending RO to EMDECS from mobile anymore and would be approved from cloud

**Comment by giovanicani** [comment]
correct. Works.
