### ISSUE TITLE
Cloud: Part Screen - Audit Log

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#11]
Please remove all these extra columns, it should work like all the other audit logs on the system

Date / Time
Change description
User

All the details of the change will go on the change description.

![image](https://cloud.githubusercontent.com/assets/5666297/12203181/97f1335a-b5fb-11e5-9528-2711416e2e94.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
All extra columns are removed. Please see attached screenshot 

![screenshot_669](https://cloud.githubusercontent.com/assets/13255706/12345643/a15c234c-bb6d-11e5-96d7-8a3cfccf031f.png)

Ready for testing in development environment.

**Comment by giovanicani** [comment]
okay
