### ISSUE TITLE
Cloud: Vendor Screen not working

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#111]
Vendor screen is not saving, please make sure it works and it is within standard.

- Also allow multiple emails to be entered on the email field (add empty text, indicating separator). Validate email format after leaving field or when saving

- Change notes from CLOB to varchar2(2000)

- Add 2 checkbox at the top: [  ] Vendor and another [  ] Supplier, add vendor_flag and supplier flag on table and field, VARCHAR2(1) NOT NULL, DEFAULT N

- Change "Preferred Supplier" to "Preferred Vendor / Supplier"

- Double the height of the notes field.

- Make sure user can add and remove taxes

- Make sure all gets recorded on audit log.

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Following points have been done:

- Checkboxes have been added
- Preferred supplier has been renamed
- Notes field has been doubled in height

Work in progress on the rest of points. We will update once it is ready in dev enironment

**Comment by giovanicani** [comment]
almost done, Rabia will update the ticket by early tomorrow.

**Comment by d3sqa** [comment]
Following points have been done:

1. Multiple emails have been incorporated. They can be separated via , or ;
2. Notes data type has been changed to varchar2(2000)
3. Check boxes has been added
4. Renamed "Preferred Supplier" to "Preferred Vendor / Supplier"
5. Doubled the height of the notes field
6. Adding and deletion of taxes has been incorporated
7. Activities are now logged at the audit log

Ready to test in development environment

**Comment by giovanicani** [comment]
- Cannot close the Province / State drop down list. Tried clicking out, tab, etc... it doesnt close, cannot save or close popup. Issue happens when creating or updating.
- Is the lat and long being calculated if address is valid ? (do not show zero if not found)
- The email field should be longer, please place it on top of the notes, so it can stretch the 2 columns.
- On the Listing Grid, please pul the add supplier on the right, as per standard. Right now it is lost on the left.

... all the other changes done seem good thanks...

![image](https://cloud.githubusercontent.com/assets/5666297/15262367/e53307f0-192f-11e6-9a67-54a08eebfa76.png)

![image](https://cloud.githubusercontent.com/assets/5666297/15262402/231db204-1930-11e6-8d23-1e5d3ff86387.png)

**Comment by d3sqa** [comment]
@giovanicani, we are unable to replicate the first point as the province drop down works fine.

Regarding the location co-ordinates, the application will always display the co-ordinates when google API returns data. If the google api is returning data for invalid address, it will be displayed. If data is 0, 0 will be displayed. If no data returned, no data will be displayed

![123333333](https://cloud.githubusercontent.com/assets/13255706/15268405/dd64cd84-19f6-11e6-8b9d-0faea62b9c3f.png)

Work in progress on other points

**Comment by d3sqa** [comment]
+ Add Supplier has been moved to right side and the email field has been re-arranged

![123newwwww](https://cloud.githubusercontent.com/assets/13255706/15268498/3f5a831e-19fa-11e6-9be5-27296b24ed97.png)

Ready to test in development environment

**Comment by giovanicani** [comment]
Cannot test on the PC provided by Tufail. Same issue with drop down list happens. Cannot close.

**Comment by giovanicani** [comment]
Please look into the email red field issue.

![image](https://cloud.githubusercontent.com/assets/5666297/15320925/3619cb44-1c01-11e6-9d71-640e97406531.png)

**Comment by d3sqa** [comment]
Multiple email validation issue has been fixed.
The email domain validation has also been applied so if the user enters test@test1.com, the application will highlight the field as 'test1' is not a valid email domain

Ready to test in development environment

**Comment by giovanicani** [comment]
thanks!
