### ISSUE TITLE
Cloud: RO Detail Screen - Send Email to mechanic when selected

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#112]
When selecting a mechanic AND SAVING, if mechanic email on the ym_users_wv is not null.

Send RO #, Trailer (Preferred #) and on the body the internal notes.

**Comment by d3sqa** [comment]
Done. Testing is in progress. 
We Will update the ticket when its ready to be tested at your end

**Comment by d3sqa** [comment]
Done on RO Detail screen. The email will be sent to the mechanic whenever the RO form is SAVED or SAVE & CLOSED. Please see screenshot below:

![capture234](https://cloud.githubusercontent.com/assets/13255706/15205617/51656e94-1832-11e6-94ef-db0d9d1ec867.png)

Test has been executed on RO with a status 'Not Assigned' as we have 'Assigned To' drop down is enabled there

**Comment by giovanicani** [comment]
okay thanks!
