### ISSUE TITLE
Cloud: RO Detail Screen - Add Labour History Tab 

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#113]
Add after tab Labour and Parts, a new tab called Labour History that will show history of labour / part for unit selected on the header (RO#, Date, Labour, Mechanic, Part). Labour will repeat, if multiple parts, but that is OK.

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
@giovanicani, should we take care of RO statuses here i.e. only those labours would reflect whose ROs are in EMDECS OK status ? or should it be open i.e. labours would be picked up from all statuses ?

**Comment by giovanicani** [comment]
Please show ROs that have the completed date not null and are not voided.

**Comment by d3sqa** [comment]
Labour History tab has been incorporated. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/15288551/2961029a-1b85-11e6-9198-1c2e7bd98f7f.png)

Column sequence has been kept same as stated above. ROs which have completed date Not Null and which are not voided are displayed in the labour history tab.

Ready to test in development environment

**Comment by giovanicani** [comment]
- Please place mechanic before labour column.
- Show 50 records by default 
- Show lines in DESC RO Date Order.

**Comment by d3sqa** [comment]
Mechanic has been places before labour. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/15317664/e53a105e-1c3b-11e6-945e-9ee826637341.png)

By default, 50 records has been displayed now. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/15317852/aa32c810-1c3c-11e6-92d2-6cbb34c40b97.png)

Records are now sorted based on the RO Date in descending order. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/15317875/cd1eb7b2-1c3c-11e6-9950-f5b219175ea4.png)

Ready to test in development environment

**Comment by giovanicani** [comment]
okay
