### ISSUE TITLE
Cloud: RO Detail Screen Allow user to split RO

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#114]
Add button so that user can select the labour lines to split, Split will create a new RO with prefix (-B, -C, etc...) with the labour selected. All parts associated to labour selected will move along with readings, and all the header information.

**Comment by d3sqa** [comment]
@giovanicani, On what statuses would the Split RO feature be enabled ? 
Should we restrict splitting RO during On hold/Approved as on hold/approved, everything is disabled for editing

**Comment by giovanicani** [comment]
Good Question... 

Split RO can be after being completed, but not approved.

After Approved, no changes are allowed including Split.

**Comment by d3sqa** [comment]
@giovanicani, what about hold status ? Should the user be allowed to split RO while it is in hold status ?

**Comment by giovanicani** [comment]
No, user cloud user cannot split while on HOLD. Needs to be completed.

**Comment by d3sqa** [comment]
@Giovani, how many time can the RO be split ? Currently we have allowed up till three times

Also, the new RO when created via splitting the RO would land into the same status as that of RO ? Currently, we have kept status same for both the Parent RO and SPLIT RO.

Please provide your feedback

**Comment by d3sqa** [comment]
Update:

- Done with the screen design
![image](https://cloud.githubusercontent.com/assets/13255706/15247101/42ca261e-192b-11e6-89f7-09f19dedbecd.png)

- RO split functionality has been implemented for copy labours

- Header has been copied entirely except Quote and Linked RO references

Work in progress on:

- Copy and remove feature
- Logging activities in audit log for both parent and child ROs

**Comment by giovanicani** [comment]
Thanks for the updates, see my notes below:

- Remove the "Copy", "Copy and Remove" radio buttons. It will always **copy and remove** the labour line
- Remove "Approve Current RO" and "Set new RO as Estimate" check box
- Splitting 2 times I believe it is OK, if the user tries to split 3 times, need to show a message saying that is not possible. Something like: "Cannot further split this RO. A RO can be split up to 2 times".
- Yes, use the same status. Split will always happen while the RO is COMPLETED but NOT APPROVED. Again: VOID, HOLD, APPROVED ROs cannot be split

## Issued parts when splitting...

Please note that to avoid problems with issued parts, the worordpar_id should not change, otherwise it will cause conflicts on the inv_inventory_audits.

**Comment by d3sqa** [comment]
- Radio buttons "Copy" and "Copy and Remove" has been removed. Also the checkboxes  "Approve Current RO" and "Set new RO as Estimate" has been removed

![image](https://cloud.githubusercontent.com/assets/13255706/15283119/7944095c-1b61-11e6-9857-8125cb8b764a.png)

- Upon splitting the RO for third time will display the following message:

![image](https://cloud.githubusercontent.com/assets/13255706/15283617/59f4f9f4-1b65-11e6-8773-6fc69e7cdfb6.png)

- When same RO is splitted twice, following message will be prompted:

![image](https://cloud.githubusercontent.com/assets/13255706/15283607/47b06a08-1b65-11e6-9d65-38de9aa77b38.png)

- RO can only be splitted in RO COMPLETE status

- The worordpar_id will not change

Ready to test in development environment

**Comment by giovanicani** [comment]
- Replace Column ESTIMATE for REASON on the split screen
- If RO has only one labour, show message: "Only ROs with multiple labour lines can be split."
- When showing message that split was done, please add a button beside OK, so that user can open the new RO in a new tab (similarly to what happens with Quote today). Label of the button could be: "View new RO".

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Estimate has been renamed to Reason. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/15314519/d75ab746-1c2b-11e6-84fa-65cde0326f44.png)

'ROs with one labour cannot be split' validation has been applied. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/15314566/28a3f1bc-1c2c-11e6-8457-84112c72a6e0.png)

View RO button and functionality has also been incorporated. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/15317218/fe29865a-1c39-11e6-9df6-1b16c3cf05f9.png)

Ready to test in development environment
