### ISSUE TITLE
Cloud: Part Screen - Price List

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#12]
User should be able to update the charge if based on = Charge. If based on percentage then all columns of the row will be read only.

Lists are automatically added here, when a new price list is created on the price list screen.

![image](https://cloud.githubusercontent.com/assets/5666297/12203221/d7c1cb5c-b5fb-11e5-8df8-fcea754d944c.png)

![image](https://cloud.githubusercontent.com/assets/5666297/12203311/48195df2-b5fc-11e5-9aab-190b40a13e8d.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by giovanicani** [comment]
please provide updated status

**Comment by d3sqa** [comment]
All parts based on percentage will be read only. Please see attachment;

![screenshot_714](https://cloud.githubusercontent.com/assets/13255706/12417807/8578fe18-becc-11e5-85e9-9c7044052b1a.png)

Ready for testing in developement environment. 

Work is in progress on following; 

- Percentage based lines will always be on top

**Comment by giovanicani** [comment]
perform changes as discussed.

**Comment by d3sqa** [comment]
Price List changes have been done as discussed. Ready for testing at development environment.

**Comment by giovanicani** [comment]
good.!
