### ISSUE TITLE
Cloud: RO Detail Screen - Ready for Billing (Send to EMDECS)

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#120]
**Only people or groups with privilege: ALLOW_BILLING_RO can check uncheck this flag ROs**

After an RO has been approved, make it available a check box called:

[  ] Ready for Billing (Send to EMDECS).

This will lock down all fields and call @gchan-trailcon procedure... More details to come.

**Comment by giovanicani** [comment]
Linked to #123 .

**Comment by d3sqa** [comment]
Ready for billing flag has been added on the APPROVED status. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/15390932/01fcfff6-1dd8-11e6-8569-303973ddb7ed.png)

Working on granting rights

**Comment by giovanicani** [comment]
As per discussion with the team, the fields are already locked after the RO was approved. So the checkbox will only call "gary's" procedure... No further locking is required.

Can you please show a popup with message: "Sending RO into EMDECS.... (work in progress)" [OK] when user clicks the "Ready for Billing" check box.

**Comment by d3sqa** [comment]
The user can check / un check based on the privilege. For testing, this privilege has been granted to user '4-master'
Pop up message has also been added. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/15393289/f9f23598-1de5-11e6-9147-3a2d584ef0d4.png)

Ready to test in development environment

**Comment by giovanicani** [comment]
okay... thanks!
