### ISSUE TITLE
MRO Link: Change Reefer Reading Validation

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#121]
When completing please change the message below:

![image](https://cloud.githubusercontent.com/assets/5666297/15085970/a6c6c08a-13ab-11e6-8cc9-f12637a89d52.png)

**Change to ...**
Please enter Reefer Readings. [OK] [Reading Not Available]

OK - Goes into the Reefer Reading Pop up.
Reading Not Available - Allows the user to Complete without any reading (similar to hubodometer validation)

**Remove message below, when pressing OK.**
![image](https://cloud.githubusercontent.com/assets/5666297/15086227/52f2a13e-13ad-11e6-9eba-68de7bc20298.png)

**Change message below from...**
![image](https://cloud.githubusercontent.com/assets/5666297/15086262/82471c62-13ad-11e6-963f-746c6b1bbec5.png)
**to...**
"Please collect On-Time and Engine Hours which are available on the Reefer."

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Upon completion, if the reefer readings are not entered, following message is displayed:

![capture](https://cloud.githubusercontent.com/assets/13255706/15091118/aa2a152c-1457-11e6-90fb-5d698114b858.PNG)

Verbiage has been changed:

![capture1](https://cloud.githubusercontent.com/assets/13255706/15091138/4b25abb2-1458-11e6-8ffe-875ee1bc003c.PNG)

Above mentioned functionality has been done and ready to test in UAT

@giovanicani, please note that while creating linked RO, if the reefer has been entered, it would prompt the user to enter the ontime as per the previous requirement. We have done the new validation on Complete button only
Please let us know if it is needed on Create Linked RO button as well

**Comment by giovanicani** [comment]
Thanks. Please remove the validation from MRO link as well. The message should only popup at complete stage.

**Comment by d3sqa** [comment]
The Reefer validation while creating a linked RO has been removed. New application updates are available at UAT

**Comment by giovanicani** [comment]
Thanks, will test and provide feedback.

**Comment by giovanicani** [comment]
works!
