### ISSUE TITLE
Cloud: RO Detail: Add a dashboard similar to Quote with categories

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#122]
Filter by Branch

ROs not Assigned
ROs Assigned / In Progress / Hold
Trailer Completed & Not Approved
Reefer/Heater Completed & Not Approved
Tires Completed & Not Approved
Approved (Trailer, Reefer, Tires) Not Billed
Sublet (Trailer, Reefer/Heater, Tires) Completed Not Approved
Sublet (Trailer, Reefer/Heater, Tires) Approved

Columns:

RO #
Age (Days)
Preferred (Trailer #)
Reefer # (only on Reefer and Approved categories)
Customer
Mechanic 
Vendor (only on Sublet 2 categories)
Serv. Location
Warranty

**Comment by d3sqa** [comment]
Update:

Design has been incorporated:

![image](https://cloud.githubusercontent.com/assets/13255706/15290184/32e465ae-1b90-11e6-8b09-e56bf17f8a20.png)

Working on adding new columns 

Question:
Are we expecting something like workflow here ? As done at the quotes screen ?

**Comment by giovanicani** [comment]
Work Flow is not expected on this screen. We will control based on FLAG type fields on the rep_work_orders_wv.

**Comment by d3sqa** [comment]
RO Dashboard has been added. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/15317914/03d3c7de-1c3d-11e6-9cf3-c72a4a1a0b14.png)

Reefer column will be displayed in Reefer/Approved category. Please see screenshots below:

![image](https://cloud.githubusercontent.com/assets/13255706/15318014/7473d7ea-1c3d-11e6-898e-cc747851ae2a.png)

![image](https://cloud.githubusercontent.com/assets/13255706/15318023/7d4056a0-1c3d-11e6-9575-1f07e5674d26.png)

![image](https://cloud.githubusercontent.com/assets/13255706/15318037/88674688-1c3d-11e6-93b6-dc1d7a1e38f5.png)

Vendor column will be displayed in the Sublet categories. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/15317992/534a371c-1c3d-11e6-8e34-efb083259dc8.png)

![image](https://cloud.githubusercontent.com/assets/13255706/15318001/5e162aac-1c3d-11e6-93c1-7e3da21c2ecc.png)

Ready to test in development environment

**Comment by giovanicani** [comment]
Please make sure that on the dashboard screen we are using the field rep_work_orders_wv.loc_id to filter the records. 
Rabia to confirm.

**Comment by d3sqa** [comment]
@giovanicani, we are using loc_id at the dashboard form from rla_locations_wv

**Comment by giovanicani** [comment]
thanks.
