### ISSUE TITLE
Cloud: Physical Count... add in progress feedback when generating list

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#125]
Hi, please add that ball in progress after user pressed Generate List. Right now there is no feedback when user is running the generation list.

![image](https://cloud.githubusercontent.com/assets/5666297/15119458/0c9eddfe-15df-11e6-853d-b09481a4e2f2.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Loader has been implemented upon clicking the Generate List button
Ready to test in development environment

**Comment by giovanicani** [comment]
okay
