### ISSUE TITLE
Cloud: Readings Tweak to make it easier search units

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#126]
This is a continuation of #101.

This is a screen that will be heavily used by users, and very important for billing, please to the following further improvements... 

1. Cut size of reading column in half
2. Add Owner as the first column. Customer code is enough as the column content
3. Make sure RTMI and RO numbers have a hyperlink to a new tab and shows the RTMI or RO record
4. Improvements on the filter as per below:
![image](https://cloud.githubusercontent.com/assets/5666297/15203159/f582385e-17ce-11e6-9080-1e804a7d1d6e.png)

**Comment by d3sqa** [comment]
Above mentioned changes have been incorporated. Please see screenshots below:

Owner column has been added:

![image](https://cloud.githubusercontent.com/assets/13255706/15209349/fd302e46-1849-11e6-9882-3f4d548b86df.png)

Hyperlinks for RO and RTMI have been provided:

![image](https://cloud.githubusercontent.com/assets/13255706/15209398/364c126c-184a-11e6-890f-a25cee7605eb.png)

Changes to the filter has been done:

![image](https://cloud.githubusercontent.com/assets/13255706/15209426/5a933dd0-184a-11e6-8029-06ff156495b4.png)

![image](https://cloud.githubusercontent.com/assets/13255706/15209433/6686c418-184a-11e6-9433-0613faefa819.png)

Ready to test in development environment

**Comment by giovanicani** [comment]
thanks!
