### ISSUE TITLE
Cloud: Receiving and Transfer Screens - Please lock the Date field on the header

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#127]
As discussed, to avoid OH conflict please lock the date fields, make them always read only. They will be populated with the date the Transfer or the Receiving was created.

Get_onhand function there are 3 parameters, the 3rd is the date. Please use the date from the header when calculating the OH on these 2 screens. DO NOT use NULL or SYSDATE / SYSTIMESTAMP (which are the current date and time)

**Comment by d3sqa** [comment]
The Transfer Date and Receiving dates have been locked on the respective screens.
Also, the date and time on the header is now passed to the Get_onhand functional instead of SYSDATE

**Comment by giovanicani** [comment]
okay.
