### ISSUE TITLE
Database Drop unused columns: ADM_TAXES and ..._WV

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#129]
- Please drop columns from ADM_TAXES and ADM_TAXES_WV

cus_id, 
last_update_username, 
last_insert_username, 
last_insert_date,
tax_id_fuel_tax_rebate
fuel_tax_rebate_eligible_flag
fuel_tax_rebate_flag
fuel_tax_flag

**Comment by d3sqa** [comment]
The above mentioned columns have been dropped from ADM_TAXES table.
Ready to test in development environment

**Comment by giovanicani** [comment]
okay.
