### ISSUE TITLE
Cloud: Question: Which table is being used to store Price Lists ?

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#13]
I have these 2 tables:

 inv_part_contracts;
 INV_PART_CHG_CONT_OVERRIDES;

Are you guys using the tables, or created new ? Thanks.

**Comment by d3sqa** [comment]
We are using INV_PART_CONTRACTS table to store Price Lists

**Comment by giovanicani** [comment]
ok good thanks.
