### ISSUE TITLE
Cloud: RO Detail Screen - Add Branch (loc_id) to the screen

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#131]
Branch is based by default on the user that created the RO on Mobile or Cloud. Branch can be changed by the user.

When RO is approved, branch can no longer be changed.

**Comment by d3sqa** [comment]
Done on Add form. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/15357447/53a3056e-1d18-11e6-89c3-f7340ba36dba.png)

Work in progress on edit form

**Comment by giovanicani** [comment]
great thanks!
