### ISSUE TITLE
Cloud: RO Detail Screen - Place billing notes on the Header of the screen after customer is selected

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#132]
Similarly to the Quote, place the notes on the header of the screen.

Remove the message below:
![image](https://cloud.githubusercontent.com/assets/5666297/15301242/c625d016-1b7a-11e6-9442-7eca9f8ade67.png)

**Comment by d3sqa** [comment]
The billing notes are now displayed at the Create RO form. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/15356212/e0679486-1d10-11e6-87c1-e907fa31331e.png)

We are working to display billing notes on Edit RO

**Comment by giovanicani** [comment]
Pending on UPDATE from.

**Comment by d3sqa** [comment]
Billing notes have been displayed on the Edit RO form as well. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/15424954/d523cf88-1e9e-11e6-90bf-4e35614be65b.png)

Ready to test in development environment

**Comment by giovanicani** [comment]
okay.
