### ISSUE TITLE
Database: Create 3 MOB Tables to store original RO information

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#135]
Please create

mob_work_orders and (_wv): same as rep_work_orders
mob_work_order_labour and (_wv): same as rep_work_order_labour
mob_work_order_parts and (_wv): same as rep_work_order_parts

MOB tables are populated when Mobile Completes RO on the tablet.

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Following tables have been created:

1. mob_work_orders and (_wv)
2. mob_work_order_labour and (_wv)
3. mob_work_order_parts and (_wv)

Ready at development environment

**Comment by giovanicani** [comment]
okay.
