### ISSUE TITLE
Cloud: Part Screen - Stock availability, parts on multiple locations

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#14]
How to handle parts stored in multiple areas ? Create new tables, or extra fields on the same table.

**Comment by giovanicani** [comment]
Use: Inv_Warehouse_Stocks_Wv (drop columns: last_insert_username, last_update_username, last_insert_date).

**Comment by giovanicani** [comment]
resolved, we will create four new fields, so that we have up to 2 sets of locations.

**Comment by giovanicani** [comment]
Please add 4 more fields to the table, view:
bin_number_2		VARCHAR2(15)
row_number_2		VARCHAR2(15)
shelf_2			VARCHAR2(15)
bin_number_2		VARCHAR2(15)

This fields should be available on the screen for user to enter, in case part is stored in more than one location within the warehouse.

**Comment by d3sqa** [comment]
Done. Above mentioned fields are added to the table. Please see attachment below;

![img_23012016_123137](https://cloud.githubusercontent.com/assets/13255706/12542691/3b9f474a-c348-11e5-9744-2e761309df05.png)

**Comment by giovanicani** [comment]
Thanks
