### ISSUE TITLE
Cloud: Parts Screen : Markup Group incorrect

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#15]
Markup group should be based on the Description of the screen below, and not on the PERCENTAGE / CHARGE fixed values.

![image](https://cloud.githubusercontent.com/assets/5666297/12463506/e097bc6a-bf91-11e5-8578-68ade5d73a65.png)

![image](https://cloud.githubusercontent.com/assets/5666297/12463543/0a3b6300-bf92-11e5-8644-dffced33334b.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Markup group will be now based on Description. Please see attachment below;

![screenshot_730](https://cloud.githubusercontent.com/assets/13255706/12579035/9be87e60-c446-11e5-912b-0ce0b11e2bf8.png)

**Comment by giovanicani** [comment]
fixed
