### ISSUE TITLE
Cloud: Part : Make notes bigger field

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#16]
Make the notes a much bigger field across the bottom of the parts screen. Needs to be multi-lined:

Change emptyText to "Enter instructions or special notes associated to this part. Notes on this box are available to the mobile mechanics on the parts selection."

**Comment by d3sqa** [comment]
Work is in progress

**Comment by d3sqa** [comment]
Notes field is now bigger across the bottom of the parts screen. Please see attachment;

![screenshot_723](https://cloud.githubusercontent.com/assets/13255706/12476443/22099402-c04b-11e5-9271-db5c2a0e6977.png)

Ready for testing in development environment.

**Comment by giovanicani** [comment]
please double height.

**Comment by d3sqa** [comment]
Notes field's height has been doubled now. Please see attachment;


![screenshot_75](https://cloud.githubusercontent.com/assets/13255706/13073769/51d58520-d4c2-11e5-88a7-1d826d9d2c04.png)

**Comment by giovanicani** [comment]
good. thanks
