### ISSUE TITLE
Cloud: Change tab label on parts screen

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#2]
Change tab label on parts detail screen from Preferred Supplier to "Override Supplier by Branch".

![image](https://cloud.githubusercontent.com/assets/5666297/12201905/bd90d072-b5f4-11e5-874b-bc5a254c0088.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Preferred Supplier tab has been renamed to 'Override Supplier by Branch'. Ready to test in development environment

![image](https://cloud.githubusercontent.com/assets/13255706/12215576/b9ca9298-b6e4-11e5-8344-cd9752ca5c00.png)


![image](https://cloud.githubusercontent.com/assets/13255706/12215577/c54eee5c-b6e4-11e5-89c2-5512d9525f99.png)

**Comment by giovanicani** [comment]
ok thanks!
