### ISSUE TITLE
Cloud: Receiving Screen

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#20]
Receiving Listing:

- By default show finalized receivings is unchecked
![image](https://cloud.githubusercontent.com/assets/5666297/12904693/3f0b27b6-ce9f-11e5-86e1-547287e8cb77.png)

Details:
![image](https://cloud.githubusercontent.com/assets/5666297/12904726/6b4abf9e-ce9f-11e5-81e8-7147446de493.png)

Taxes / Surcharges:
![image](https://cloud.githubusercontent.com/assets/5666297/12904735/843c4496-ce9f-11e5-8e7c-2328c97f132b.png)

Report / Email:
![image](https://cloud.githubusercontent.com/assets/5666297/12904790/c6122c3c-ce9f-11e5-997a-f393a2394a8a.png)

**Comment by giovanicani** [comment]
Tables (WV Views)

**inv_inventory_receivings (inv_inventory_receivings_wv)**
- Drop column CUS_ID
- Drop column LAST_INSERT_USERNAME, LAST_UPDATE_USERNAME, LAST_INSERT_DATE
- Change notes to varchar2(2000) instead of CLOB
- Make sure audit trigger takes in consideration context variable

**inv_inventory_rcv_details (inv_inventory_rcv_details_wv)**
- Drop column GLACC_ID
- Rename QTDY_CONVERSION to QTY_CONVERSION
- Make sure audit trigger takes in consideration context variable

**Not needed at this point - inv_inventory_receiving_taxes (inv_inventory_receiving_tax_wv)**

**Not needed at this point - inv_inventory_rcv_other_costs (inv_inventory_rcv_other_cos_wv)**

**Comment by d3ssupport** [comment]
Work in Progress!

**Comment by giovanicani** [comment]
kindly provide brief update. Thanks!

**Comment by d3sqa** [comment]
RO Listing and RO Detail screen design has been completed. Please see attachment below;

![screenshot_14](https://cloud.githubusercontent.com/assets/13255706/13249934/e8810ee6-da48-11e5-8f1d-d136890aa6a2.png)

![screenshot_13](https://cloud.githubusercontent.com/assets/13255706/13249939/edfe5040-da48-11e5-864b-2a7d8282855f.png)

Work in progress on its functionality.

**Comment by d3sqa** [comment]
Work in progress on 'Add receiving', 'Part deletion' and 'New Part' functionality.

**Comment by giovanicani** [comment]
Create Receiving from PO:

![image](https://cloud.githubusercontent.com/assets/5666297/13286322/a53a90a4-dace-11e5-9ae6-82148bdc5d58.png)

![image](https://cloud.githubusercontent.com/assets/5666297/13286328/adad48e4-dace-11e5-845e-16b8aec12688.png)

**Comment by d3sqa** [comment]
Work in progress on creating receiving from PO

**Comment by d3sqa** [comment]
The Create Receiving feature has been incorporated. Functionality of edit receiving has also been done and ready to test in development environment

![image](https://cloud.githubusercontent.com/assets/13255706/13911707/ca2e1f48-ef55-11e5-9d3c-8ea99964688b.png)

![image](https://cloud.githubusercontent.com/assets/13255706/13911712/de020a20-ef55-11e5-9593-122c4ac19160.png)

**Comment by giovanicani** [comment]
done.
