### ISSUE TITLE
Cloud: Parts Screen, preferred supplier tweak.

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#21]
Add tooltip on the preferred supplier field

![image](https://cloud.githubusercontent.com/assets/5666297/13077249/93ba9210-d485-11e5-8507-f4b4141e4109.png)

"If blank this part may not be selected on the auto-reordering process"

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Tooltip has been added in 'Preferred Supplier' field. Please see attachment;

![screenshot_20](https://cloud.githubusercontent.com/assets/13255706/13142669/77186baa-d660-11e5-8722-a7eaf3c140b8.png)


Ready for testing at development environment.

**Comment by giovanicani** [comment]
good.
