### ISSUE TITLE
Cloud: Parts Screen - Conversion To Stocking UOM

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#22]
On the field below, please add tooltip
![image](https://cloud.githubusercontent.com/assets/5666297/13077297/e030646c-d485-11e5-8991-9346857e6e28.png)

Conversion rate from ordering to stocking. I.e.: 1 Dozen = 12 EA, rate is 12.

**Comment by giovanicani** [comment]
**Make default value = 1**

**Comment by d3sqa** [comment]
Tooltip has been added in 'Conversion to Stocking UOM' field. Please see attachment;

![screenshot_19](https://cloud.githubusercontent.com/assets/13255706/13136794/4eb7e8ba-d63e-11e5-8caa-3f6765e096e6.png)


Ready for testing at development environment.

**Comment by giovanicani** [comment]
works. thanks!
