### ISSUE TITLE
Cloud: Parts Screen - Standard Cost

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#23]
Make field mandatory, with red asterisk.

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Standard cost field is now mandatory. Please see attachment;

![screenshot_9](https://cloud.githubusercontent.com/assets/13255706/13106076/342d4ae6-d588-11e5-837c-374382da05fa.png)


Ready for testing at development environment.

**Comment by giovanicani** [comment]
good. thanks.
