### ISSUE TITLE
Cloud: Parts Screen - Supplier Catalog is not 100%

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#24]
- Description should auto populate
- Red boxes around fields ?

![image](https://cloud.githubusercontent.com/assets/5666297/13077427/a8ccacaa-d486-11e5-910a-cecd1d5b1493.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Description will be auto-populated now and can be editable also. Please see attachment;

![screenshot_25](https://cloud.githubusercontent.com/assets/13255706/13168800/16fd3992-d702-11e5-9443-fa271f1f5d79.png)


Ready for testing at development environment.

**Comment by giovanicani** [comment]
skylook down. not able to test.

**Comment by giovanicani** [comment]
good thanks
