### ISSUE TITLE
Cloud: Part Screen - Override Supplier by Branch not 100%

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#25]
- Should not allow more than 1 line per branch
- Date validation (expire can be blank or higher than effective)
- No feedback on save.

![image](https://cloud.githubusercontent.com/assets/5666297/13077470/fb53f9c4-d486-11e5-8e3a-8075b03a136b.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Date validation has been applied at 'Override Supplier by branch' tab and one line per branch is allowed for user. Please see attachment;

![screenshot_26](https://cloud.githubusercontent.com/assets/13255706/13171937/3c8acea8-d717-11e5-95ec-1efa77baeac3.png)


Ready for testing at development environment.

**Comment by giovanicani** [comment]
good thanks!
