### ISSUE TITLE
Cloud: Part Screen - Stock Availability tab space issues

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#26]
As discussed there are space issues on this screen:
- Inventory too long
- On hand too long
- Room too long
- Make rack shelf bin longer
- Add some sort of reference (tooltip or red label at the top) that min and max quantities are based on stocking UOM.

![image](https://cloud.githubusercontent.com/assets/5666297/13077531/4ba25646-d487-11e5-881a-3f3777fb7cd2.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Space issue has been fixed and Label is added at the top. Please see attachment;

![screenshot_22](https://cloud.githubusercontent.com/assets/13255706/13142091/b637cde8-d65c-11e5-8224-2adf8164e662.png)



Ready for testing at development environment.

**Comment by giovanicani** [comment]
good thanks!
