### ISSUE TITLE
Cloud: Part Screen - Need to be able to delete ...

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#27]
- Override Supplier by Branch
- Supplier Catalog

Perhaps adding a garbage bin at the end of each line  ??

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Delete option has been added at 'Override Supplier by Branch' tab and 'Supplier Catalog' tab. Please see attachment;

![screenshot_33](https://cloud.githubusercontent.com/assets/13255706/13196311/61639b6c-d7ec-11e5-84e8-0c573317ee1c.png)

![screenshot_35](https://cloud.githubusercontent.com/assets/13255706/13196443/68943aec-d7ef-11e5-84a5-fbbb807fd0f0.png)


Ready for testing at development environment.

**Comment by giovanicani** [comment]
skylook down. not able to test.

**Comment by giovanicani** [comment]
works. thanks
