### ISSUE TITLE
Cloud: Part Screen - Avg Cost

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#3]
Average cost should always read only

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Average Cost field is now read only at both Add and Update Part. Ready to test in development environment

![image](https://cloud.githubusercontent.com/assets/13255706/12215614/c16d725c-b6e6-11e5-8cdd-da627a1fedb0.png)

**Comment by giovanicani** [comment]
okay
