### ISSUE TITLE
Cloud: Inventory Inquiry (Real Time)

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#30]
Screen to monitor inventory transactions in real time.

Screen that shows all transactions on the inventory based on the inventory_audits table.

![image](https://cloud.githubusercontent.com/assets/5666297/13294529/5c19b688-daf2-11e5-88e6-33c11f68a2b1.png)

**Comment by giovanicani** [comment]
**WV View: inv_inventory_audits_wv**

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Inventory inquiry screen has been implemented and updated in real time. Please see below screenshot:

![image](https://cloud.githubusercontent.com/assets/13255706/13911768/767a06c2-ef56-11e5-938b-6fdb195b37e5.png)

Ready to test in development environment

**Comment by giovanicani** [comment]
done.
