### ISSUE TITLE
Database: On Hand Calculation Instructions

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#31]
This is one of the critical functions below is a sample of the code... Convert into Oracle and put into the standards that we've been using.

```sql
/* Code written in MySQL */
FUNCTION get_part_onhand(p_war_id INT(10), p_par_id INT(10), p_asof_date DATETIME) RETURNS DECIMAL(10,2)
    READS SQL DATA
    DETERMINISTIC
BEGIN
	
	DECLARE v_onhand_qty      DECIMAL(10,2) DEFAULT 0;
	DECLARE v_asof_date		  DATETIME;

	IF (p_asof_date IS NULL) THEN
		SET v_asof_date = now();
	ELSE
		SET v_asof_date = p_asof_date;
	END IF;

/* TODO on the query below: Instead of reading all transaction for the p_par_id in the inventory (p_war_id), go back to last physical count before p_asof_date get the count and start calculating from there */	

	SELECT IFNULL(SUM(quantity),0) onhand_qty 
	INTO   v_onhand_qty
	FROM   inv_inventory_audits_wv
	WHERE  par_id = p_par_id
	AND    war_id = p_war_id
	AND    transaction_timestamp <= v_asof_date
    	
	RETURN v_onhand_qty;
	
END
```

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
We are done with the procedure. Need your feedback on it:

 FUNCTION PRC_GET_PART_ONHAND (
                             PI_PAR_ID     IN NUMBER,
                             PI_WAR_ID     IN NUMBER,
                             PI_ASOF_DATE   IN TIMESTAMP)RETURN  NUMBER
                             IS 
                             
                             V_ONHAND_QTY  NUMBER;
                             V_ASOF_DATE   TIMESTAMP;                            
BEGIN 
  
                                 
     IF PI_ASOF_DATE IS NULL THEN
        V_ASOF_DATE := SYSTIMESTAMP;
    ELSE
        V_ASOF_DATE := PI_ASOF_DATE;
    END IF;
--- CALCULATE ONHAND
SELECT NVL(SUM(QUANTITY),0) ONHAND_QTY 
    INTO   V_ONHAND_QTY
    FROM   INV_INVENTORY_AUDITS_WV
    WHERE  PAR_ID = PI_PAR_ID
    AND    WAR_ID = PI_WAR_ID
    AND    TRANSACTION_TIMESTAMP <= V_ASOF_DATE;

    RETURN (V_ONHAND_QTY);
EXCEPTION
  WHEN OTHERS THEN
  RETURN (0);
END PRC_GET_PART_ONHAND; \

**Comment by giovanicani** [comment]
I don't like the when others! Needs to raise an error, and not just return ZERO.
use:
```sql
RAISE_APPLICATION_ERROR(-20001, 'Error on onhand calculation: '||SQLCODE||'-'||SQLERRM);
```

**Comment by giovanicani** [comment]
please update with latest procedure so that it can be closed.

**Comment by d3sqa** [comment]
Please find below the updated procedure:

```sql
FUNCTION PRC_GET_PART_ONHAND (
                             PI_PAR_ID     IN NUMBER,
                             PI_WAR_ID     IN NUMBER,
                             PI_ASOF_DATE   IN TIMESTAMP)RETURN  NUMBER
                             IS 
                             
                             V_ONHAND_QTY  NUMBER;
                             V_ASOF_DATE   TIMESTAMP;                            
BEGIN 
      IF PI_ASOF_DATE IS NOT NULL THEN
      V_ASOF_DATE:=TO_CHAR(PI_ASOF_DATE,'DD-MON-YY HH:MI:SS');
      ELSE
      V_ASOF_DATE:='';
      END IF;
--- CALCULATE ONHAND                                 
    SELECT NVL(SUM(QUANTITY),0) ONHAND_QTY 
    INTO   V_ONHAND_QTY
    FROM   INV_INVENTORY_AUDITS_WV
    WHERE  PAR_ID = PI_PAR_ID
    AND    WAR_ID = PI_WAR_ID
   AND     TO_CHAR(TRANSACTION_TIMESTAMP,'DD-MON-YY HH:MI:SS') <= V_ASOF_DATE;
      END IF; 
    RETURN (V_ONHAND_QTY);
EXCEPTION
   WHEN OTHERS THEN
   RAISE_APPLICATION_ERROR(-20001,'An error was encountered - '||SQLCODE||' -ERROR- '||SQLERRM);
END PRC_GET_PART_ONHAND;

**Comment by giovanicani** [comment]
good! thanks
