### ISSUE TITLE
Database: Get part cost instructions

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#32]
**Please have a function similar to this on the package to retrieve the part cost. It will be used in many places within the inventory and accounting module**
```sql
FUNCTION get_part_cost_amount(p_par_id INT(10)) RETURNS decimal(10,4)
    READS SQL DATA
    DETERMINISTIC
BEGIN

    DECLARE v_cost_amount,
            v_last_purchase_cost, 
            v_average_cost, 
            v_standard_cost DECIMAL(10,4) DEFAULT 0;
            
    DECLARE v_markup_based_on VARCHAR(10);
            
    
    SELECT IFNULL(par.last_purchase_cost,0)  last_purchase_cost,
           IFNULL(par.average_cost,0)        average_cost      ,
           IFNULL(par.standard_cost,0)       standard_cost     ,
           IFNULL(par.markup_based_on,'STD') markup_based_on
    INTO   v_last_purchase_cost,
           v_average_cost      ,
           v_standard_cost     ,
           v_markup_based_on
    FROM   inv_parts par
    WHERE  par.par_id = p_par_id;


    IF (v_markup_based_on = 'STD') THEN
    
        SET v_cost_amount = v_standard_cost;
        
    ELSEIF (v_markup_based_on = 'AVG') THEN
    
        SET v_cost_amount = v_average_cost;
        
    ELSEIF (v_markup_based_on = 'LASTP') THEN
    
        SET v_cost_amount = v_last_purchase_cost;
    
    END IF;
    
    RETURN v_cost_amount;

END
```

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
We are done with its procedure. Need your feedback on it:


FUNCTION PRC_GET_PART_COST_AMOUNT (
                                  PI_PAR_ID  IN NUMBER)RETURN NUMBER
                                  IS
                                  
                                  V_COST_AMOUNT           NUMBER:=0;
                                  V_LAST_PURCHASE_COST    NUMBER:=0;
                                  V_AVERAGE_COST          NUMBER:=0;
                                  V_STANDARD_COST         NUMBER:=0;  
                                  V_MARKUP_BASED_ON       VARCHAR2(20);
BEGIN
  
SELECT NVL(PAR.LAST_PURCHASE_COST,0)      LAST_PURCHASE_COST,
           NVL(PAR.AVERAGE_COST,0)        AVERAGE_COST      ,
           NVL(PAR.STANDARD_COST,0)       STANDARD_COST     ,
           NVL(PAR.MARKUP_BASED_ON,'STD') MARKUP_BASED_ON
    INTO   V_LAST_PURCHASE_COST,
           V_AVERAGE_COST      ,
           V_STANDARD_COST     ,
           V_MARKUP_BASED_ON
    FROM   INV_PARTS_WV PAR
    WHERE  PAR.PAR_ID = PI_PAR_ID;
--- RETERIVE COST
    IF  V_MARKUP_BASED_ON = 'STD' THEN
        V_COST_AMOUNT:= V_STANDARD_COST;
    ELSIF V_MARKUP_BASED_ON = 'AVG' THEN
        V_COST_AMOUNT:= V_AVERAGE_COST;
    END IF;   

 RETURN (V_COST_AMOUNT);
    EXCEPTION
      WHEN OTHERS THEN
        RETURN (0);
    
END PRC_GET_PART_COST_AMOUNT;

**Comment by giovanicani** [comment]
closed.
