### ISSUE TITLE
PO / RCV / Transfer / PC: Use inv_warehouses(_wv) for Inventory 

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#34]
1. Please only show records for selection that have active_flag = Y
2. Drop cus_id from table and view
3. Drop last_insert_username, last_update_username, last_insert_date
4. Make sure that the audit trigger is in the standard (context variables)

**Comment by d3sqa** [comment]
Point #01 through 04 have been done
