### ISSUE TITLE
PO / RCV / Transfer / PC: Default Inventory should be logged user default.

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#35]

**Comment by d3sqa** [comment]
The user's default inventory is displayed at Purchase Order, Receiving and Physical Count. Ready to test in development environment

Work in progress on Transfer

**Comment by d3sqa** [comment]
Done at Transfer screen as well. Ready to test in development environment

**Comment by giovanicani** [comment]
works.
