### ISSUE TITLE
PO / RCV / Transfer / PC: All Quantities should allow negative quantity (return)

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#36]

**Comment by d3sqa** [comment]
Negative QTY has been incorporated in Purchase Order, Receiving and Transfer
Work in progress on Physical Count screen

**Comment by giovanicani** [comment]
No need on PC, sorry. PO, RCV and Transfer only. Thanks!

On Sat, Mar 19, 2016 at 8:57 AM, d3sqa <notifications@github.com> wrote:

> Negative QTY has been incorporated in Purchase Order, Receiving and
> Transfer
> Work in progress on Physical Count screen
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/GCSO2/D3S-INVENTORY/issues/36#issuecomment-198697568>
>



-- 
Giovani Cani
Project Manager (PMP, CSM & OCP)
Software Delivery Services
