### ISSUE TITLE
Cloud: PO: Assign RO popup box

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#37]
As discussed:

![image](https://cloud.githubusercontent.com/assets/5666297/13427614/2cb281be-df83-11e5-8348-055e81bb90e7.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Assign RO pop up has been implemented at PO screen. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/13593410/c509d7ac-e51c-11e5-8cfb-19e47eb08665.png)


![image](https://cloud.githubusercontent.com/assets/13255706/13593432/f038bb28-e51c-11e5-920c-0491c5ff3082.png)

**Comment by giovanicani** [comment]
when Remove Assignment / Assign / Re - assign was completed, just close the popup.

Please replace mechanic username with name.

**Comment by d3sqa** [comment]
The RO Assign/Un-Assign RO pop up will be closed as soon as the user assigns or un-assigns the RO. Mechanic name is also being displayed at the pop up.

Whenever the RO is assigned against a part and that part is clicked, the pop up will be populated with the relevant data. See screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/13912359/0b5fdc7e-ef5e-11e5-8d7b-a98747d5c615.png)

**Comment by giovanicani** [comment]
done.
