### ISSUE TITLE
Cloud: Menu Sequence

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#38]
As discussed, update the menu buttons to the following sequence ...

1. Purchase Order
2. Receiving
3. Transfer
4. Physical / Cycle Count
5. Inquiry
6. Part Maintenance (new button)

![image](https://cloud.githubusercontent.com/assets/5666297/13430318/87948d52-df92-11e5-856f-5f626b519db1.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Dashboard as per above requirement has been implemented. Ready to test in development environment. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/13459921/f35d3c08-e098-11e5-8b09-b019c8be727a.png)

**Comment by giovanicani** [comment]
looks good thanks!
