### ISSUE TITLE
Cloud: PO Screen: Part Column Details

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#39]
This item is associated with #19 

Please adjust columns as per headings below:

![image](https://cloud.githubusercontent.com/assets/5666297/13430852/cc14771a-df94-11e5-80b7-01089c469bb5.png)

Column details:

**\#** - Inline Read Only, sequential number
**Part #** - Inline Read Only,Part number
**Description** - Inline Read Only,Part description
**Core** - Inline Read Only, Indicator if it is a core or not.
**Quantity** - Inline Update, right aligned
**Ordering UOM** - Inline Updated, default value from parts table, new field: ```UOM_ID_REORDERING NUMBER NOT NULL``` ***please use the same name from the field used in the inv_parts table, not sure the name that was defined for that field.***

**Stocking UOM** - Inline Read Only, retrieve from parts table
**Negotiated Cost** - Inline Updated, default value same as cost (next column), right aligned, new field: ```COST NUMBER(10,4) NOT NULL```
**Cost** - Inline Read Only, Default cost for part (average or standard), right aligned
**Total Neg. Cost** - Inline Read Only, "Negotiated Cost" X "Quantity", right aligned
**Qty Rec'd** - Inline Read Only, from function based on receivings for this PO, right aligned
**Qty BO** - Inline Read Only, "PO Quantity" minus "Received for this PO", right aligned
**RO #** - RO # associated to the line.

\** 2 new fields should be added to table / view inv_purchase_order_details / inv_purchase_order_details_wv

**Add Estimated Grand Total (Total Neg. Cost) at the bottom of the PO.**

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
The above columns are incorporated. QTY and negotiated costs are now inline edited. We are working on inline edit of Ordering UOM.

Estimated Grand total field has been added.

Parts grid changes are also incorporated. Barcode scan feature while adding parts has also been done.

Please test in development environment

**Comment by d3sqa** [comment]
Inline edit on Ordering UOM and negotiated cost has also been incorporated at both Add PO and Edit PO forms. Please see screenshots below:

![image](https://cloud.githubusercontent.com/assets/13255706/13898690/1cc36e04-edfb-11e5-899b-73bb3ab998e5.png)

![image](https://cloud.githubusercontent.com/assets/13255706/13898697/5623360c-edfb-11e5-9a6d-4808ddf26cc3.png)

Ready to test in development environment

**Comment by giovanicani** [comment]
done.
