### ISSUE TITLE
Cloud: Part Screen - UOM Conversion & Warranty

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#4]
UOM:This is a numeric field, with 2 decimals.

![image](https://cloud.githubusercontent.com/assets/5666297/12201960/24f64724-b5f5-11e5-84c8-2bcd242f1a9e.png)

Warranty: Change the label to "Warranty (Months)", and only allow numbers, right aligned.

![image](https://cloud.githubusercontent.com/assets/5666297/12201985/5154d7e0-b5f5-11e5-8e40-b8f6fdd83a20.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by giovanicani** [comment]
please provide updated status

**Comment by d3sqa** [comment]
Label has been changed to 'Warranty (Months)' and numeric field with 2 decimals are allowed in UOM. Please see attachment;

![screenshot_715](https://cloud.githubusercontent.com/assets/13255706/12444355/579c7d76-bf80-11e5-9f39-452628a3d90a.png)

Ready for testing at development environment.

**Comment by giovanicani** [comment]
good thanks!
