### ISSUE TITLE
Reports: Add Barcode Code 128 to PO, Receiving, Transfer, Physical Count, RO and Quote

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#40]
Please add the Code 128 barcode to all reports, see example below:

![image](https://cloud.githubusercontent.com/assets/5666297/13461892/677ff018-e052-11e5-9d99-bb3e790de587.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Barcode has been incorporated at PO report. Ready to test in development environment

Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/13569772/cd3b9280-e48b-11e5-9d2a-d379a013ade7.png)

**Comment by d3sqa** [comment]
Report Email feature has also been incorporated. Ready to test in development

**Comment by giovanicani** [comment]
done.
