### ISSUE TITLE
Parts Screen: Create Interchange parts popup, user can add or remove parts.

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#44]
Create table:

**inv_part_interchanges**
[audit and ten_id fields]
parint_id
par_id
par_id_interchange

**UK: ten_id, par_id, par_id_interchange**

par_id - current part selected;
par_id_interchange - part that par_id can be replaced with;

One par_id will have 1 or n par_id_interchange, example

```
ten_id  |  parint_id  | par_id  | par_id_interchange 
1000000 |    1        |   1     |    23
1000000 |    2        |   1     |    25
1000000 |    3        |   1     |    26
1000000 |    4        |   1     |    27
1000000 |    5        |   1     |    28
1000000 |    6        |   1     |    29
1000000 |    7        |   13    |    3427
1000000 |    8        |   13    |    843
1000000 |    9        |   13    |    34229
```

**Comment by d3sqa** [comment]
Table inv_part_interchanges has been created. Work in progress on the screen

**Comment by giovanicani** [comment]
please provide update.

**Comment by tufailzafar** [comment]
Work in progress

**Comment by tufailzafar** [comment]
Testing in progress

**Comment by d3sqa** [comment]
Parts Interchange pop up has been implemented. Parts can be added and deleted. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/14076514/b0f96900-f4fb-11e5-9ca4-b7c890da31d1.png)

![image](https://cloud.githubusercontent.com/assets/13255706/14076517/b8cf3f06-f4fb-11e5-8494-33a3f34aa36f.png)

**Comment by giovanicani** [comment]
1. Add doesnt work.
2. When opening add popup box, cursor should go to description field.

Please re-test all buttons and functionalities.

**Comment by giovanicani** [comment]
![image](https://cloud.githubusercontent.com/assets/5666297/14117986/52edc300-f5b5-11e5-94ca-82cae99354aa.png)

**Comment by d3sqa** [comment]
Cursor is now displayed when the Add Part pop up is opened up.

![image](https://cloud.githubusercontent.com/assets/13255706/14171648/763675de-f74d-11e5-88a1-e553b5d7ec47.png)

Parts are now added successfully. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/14171662/8979b084-f74d-11e5-853d-08bcc05ba219.png)

Ready to test in development environment

**Comment by giovanicani** [comment]
works.
