### ISSUE TITLE
Cloud: PO Listing - Filters not working

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#46]
Including Finalized should show:

Not finalized POs + Finalized POs.

This is not happening. Please fix.

**Comment by tufailzafar** [comment]
work in progress

**Comment by d3sqa** [comment]
Whenever Including Finalized is checked, both Not finalized POs + Finalized POs will be shown. Ready to test in development environment

![image](https://cloud.githubusercontent.com/assets/13255706/14044241/09b53b6c-f2b0-11e5-9caa-ac4e93d19ff1.png)

**Comment by giovanicani** [comment]
resolved.
