### ISSUE TITLE
Cloud: PO Details - Clean Filter after add

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#47]
After adding part (double click on Add Another), clean the top filter fields.

![image](https://cloud.githubusercontent.com/assets/5666297/13952235/af37c5f2-f00b-11e5-81df-1b10263b51f2.png)

**Comment by tufailzafar** [comment]
work in progress

**Comment by d3sqa** [comment]
The filter at PO Screen is now cleared up once the part is added via Add Another or Double click

**Comment by giovanicani** [comment]
resolved. thanks.
