### ISSUE TITLE
Cloud: PO Details - Cost Lost 4 decimals

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#48]
After inline editing negotiated cost, total loses 4 decimals.

![image](https://cloud.githubusercontent.com/assets/5666297/13952292/029cffb4-f00c-11e5-848e-6e497773c300.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
4 decimal points are now retained. Ready to test in development environment:

![image](https://cloud.githubusercontent.com/assets/13255706/14010783/30010522-f1ba-11e5-965a-a33dbfc0169c.png)
