### ISSUE TITLE
Cloud: Part Screen: Average Cost, Standard Cost and Retail Price

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#5]
Allow up to 4 decimals. map the same field size as the database, right aligned.

**Comment by d3sqa** [comment]
Work in progress

**Comment by giovanicani** [comment]
please provide updated status

**Comment by d3sqa** [comment]
Up to 4 decimals are allowed in Average Cost, Standard Cost and Retail Price. Please see attachment;

![screenshot_716](https://cloud.githubusercontent.com/assets/13255706/12444483/15870a4a-bf81-11e5-993f-3122f030c605.png)


![screenshot_717](https://cloud.githubusercontent.com/assets/13255706/12444498/1e51a8d8-bf81-11e5-9d52-0295c89eaf8b.png)

Ready for testing at development environment.

**Comment by giovanicani** [comment]
radio button not selectable if Avg Cost is null

**Comment by d3sqa** [comment]
No radio button will be selectable now if average cost is null. 
Ready for testing at development environment.

**Comment by giovanicani** [comment]
okay.
