### ISSUE TITLE
Cloud: PO Details - Create Supplier does not work

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#50]
Make sure that it works, and when SAVE is pressed on the new Supplier popup box, then it should place it on the supplier box on the PO Detail screen.

**Comment by tufailzafar** [comment]
work in progress

**Comment by tufailzafar** [comment]
805 of the work done, some tweaks remaining

**Comment by d3sqa** [comment]
Create Supplier feature has been incorporated at both Add and Edit forms of PO and Receiving. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/14224786/4ccda444-f8c2-11e5-8a24-1a1346f55b4a.png)

![image](https://cloud.githubusercontent.com/assets/13255706/14224791/6da2965c-f8c2-11e5-8636-a2b335261421.png)

Also, at edit forms, when new supplier is added, the fields will be updated accordingly

Ready to test in development environment

**Comment by giovanicani** [comment]
thanks.
