### ISSUE TITLE
Cloud: PO Details - Assign RO to PO line item

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#51]
Make it searchable by mechanic name and RO #.

Show only ROs that are not completed and not voided.

![image](https://cloud.githubusercontent.com/assets/5666297/13953150/cebab056-f010-11e5-8677-19bd5eff133e.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
The search is now applied against Mechanic Name as well

![image](https://cloud.githubusercontent.com/assets/13255706/14040487/84e3d126-f289-11e5-9d22-987ad0df2a54.png)

Ready to test in development environment

**Comment by giovanicani** [comment]
resolved.
