### ISSUE TITLE
Cloud: PO / RCV / Transfer / Physical Count Details - Show default message, there are unsaved changed when closing

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#52]
1. Add note that changes are auto saved. Save at every change / addition.
2. Remove Save / Save & Close buttons
3. Change Red Cancel to Close, and make it close tab.
4. Apply this change to all 4 screens.

![image](https://cloud.githubusercontent.com/assets/5666297/13953374/13a66132-f012-11e5-9753-71062b8825ac.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by giovanicani** [comment]
After conversation, we WILL NOT do auto save, we will add a message on 2 points of the form.

When they close the browser tab and when they press cancel on the form. The message will be similar to Zendesk example discussed:


![image](https://cloud.githubusercontent.com/assets/5666297/14015906/c621cd0c-f192-11e5-8e9b-65bd71a566a4.png)


![image](https://cloud.githubusercontent.com/assets/5666297/14015911/d26968a4-f192-11e5-8a5b-f3c742e8d74b.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Auto Save feature has been incorporated on PO, Receiving, Transfer and Physical Count.

Work in progress on unsaved changes feature

**Comment by d3sqa** [comment]
Unsaved changes prompt has been displayed now whenever there are unsaved changes on Add forms of PO, Receiving, Transfer and Physical Count. Ready to test in development environment

**Comment by giovanicani** [comment]
will test thanks.

**Comment by giovanicani** [comment]
Good Job Team (and Rabia)
