### ISSUE TITLE
Cloud: PO Details - Show Supplier contact information on PO (read only)

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#54]
Show read only these fields.

![image](https://cloud.githubusercontent.com/assets/5666297/13954188/1a5d6fe4-f016-11e5-8a3f-08c4f5bb3014.png)

When sending PO to supplier pre-populate email(s) on the TO field of the email.
![image](https://cloud.githubusercontent.com/assets/5666297/13954243/5d841df4-f016-11e5-99ff-520befd0d392.png)

**Comment by d3ssupport** [comment]
Work in Progress

**Comment by d3sqa** [comment]
Supplier fields displayed on Edit PO.

![image](https://cloud.githubusercontent.com/assets/13255706/14076729/f38807a2-f4fd-11e5-92f1-735d123a965b.png)

Work in progress on populating TO email and fields on Add PO form

**Comment by d3sqa** [comment]
Done at Add PO form as well. Please check screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/14077663/66c65148-f507-11e5-815c-d796ae4e1851.png)

The email is also being populated in TO. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/14077674/7a71482e-f507-11e5-9ab6-d5eb868c2ceb.png)

Ready to test in development environment

**Comment by giovanicani** [comment]
Looks good, but text is being cut off on the first header box, can we try to make it:

45%, 25%, 30% ?

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Done. Please see screenshots below:

Add form:

![image](https://cloud.githubusercontent.com/assets/13255706/14167971/3548656a-f738-11e5-8232-3e5fa91442b8.png)

Edit Form:

![image](https://cloud.githubusercontent.com/assets/13255706/14167963/249e8ac8-f738-11e5-9062-755211dff18b.png)

Ready to test in development environment

**Comment by giovanicani** [comment]
looks better.
