### ISSUE TITLE
Cloud: Receiving Listing: Filter not working

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#55]
Include finalized checked should show : Finalized + Not Finalized

Include finalized unchecked (defaul) should show: Not finalized only

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Done. The filter is now working as per the requirement. Ready to test in development environment

**Comment by giovanicani** [comment]
works thanks!
