### ISSUE TITLE
Cloud: Receiving from PO - Not working at all.

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#56]
Need to be able to search by PO # and supplier name / code of only POs not finalized.

Notes says that was auto created based on usage ? Doesnt make sense.

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
The search has been fixed now. Search is now applied based on PO #, Supplier Name and Supplier Code

![image](https://cloud.githubusercontent.com/assets/13255706/14014784/842b8296-f1d6-11e5-8bf7-db89c443dfb8.png)

![image](https://cloud.githubusercontent.com/assets/13255706/14014793/8e791a42-f1d6-11e5-9688-637c1c073ced.png)

Ready to test in development environment

**Comment by giovanicani** [comment]
thanks resolved.
