### ISSUE TITLE
Cloud: Receiving from PO - Should be created and auto saved.

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#57]
Doesn't make sense for the user press Save right after creating the receiving from PO#.

Please make sure that it opens directly in the UPDATE form.

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Done. The receiving will be directly opened up in update form. Ready to test in development environment

**Comment by giovanicani** [comment]
works.
