### ISSUE TITLE
Cloud: Receiving Details - Change confirm verbiage

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#58]
Please change verbiage to:

Confirm finalizing the Receiving ? **After finalizing, ONHAND values will be updated. This action cannot be reverted**
Buttons: Finalize / Cancel.

After finalize is completed and received OK from database, show message: "Receiving successfully finalized." or show error if any.

![image](https://cloud.githubusercontent.com/assets/5666297/13954601/e8961f54-f017-11e5-85d6-3668aaa9bb0e.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
The verbiage has been updated. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/14013528/c165147c-f1ce-11e5-81d1-eebe4c9f85ff.png)

![image](https://cloud.githubusercontent.com/assets/13255706/14013537/cf4df6ee-f1ce-11e5-9051-6b4125f91a2f.png)

 Ready to test in development environment

**Comment by giovanicani** [comment]
okay thanks.
