### ISSUE TITLE
Cloud: Part Screen - Tire Flag

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#6]
Remove the tire flag and add it to the parts group. We will be tracking a part as tire, based on the parts group.

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Tire Flag has been removed and 'Tire' option has been added to the Inventory Group dropdown

**Comment by giovanicani** [comment]
Giovani to handle this for now.... conversations going on within Trailcon right now on the process, charge, etc...

**Comment by giovanicani** [comment]
Still need to get clarification on Tires before writing the documentation.

**Comment by giovanicani** [comment]
closed. Will create a new ticket once we have the correct  and final specification.
