### ISSUE TITLE
Cloud: Parts Detail - Add barcode on the Supplier Catalog tab.

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#62]
Add supplier catalog part barcode, (also add barcode field on the database)

Please add barcode before field Catalog #, barcode is not mandatory. 

![image](https://cloud.githubusercontent.com/assets/5666297/13959664/6b775344-f02b-11e5-9b3f-e3aa25e417a0.png)

Thanks!

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Barcode functionality has been added. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/14017478/7804296a-f1e9-11e5-8c4b-41fe72fcf61b.png)

 Ready to test in development environment

**Comment by giovanicani** [comment]
works, however audit log is not being updated with the changes, please make sure that all changes are recorded on the audit log ? Thanks!

**Comment by d3sqa** [comment]
Work in progress on audit log

**Comment by d3sqa** [comment]
Add/Edit Supplier Catalog activities are now logged at Audit Log. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/14040370/7191ea14-f288-11e5-8166-f3ccbccf080d.png)

Ready to test in development environment

**Comment by giovanicani** [comment]
resolved.
