### ISSUE TITLE
Cloud: PO Details: Add Part - Make Supplier catalog records available for selection

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#63]
- Add Catalog # field after Part #
![image](https://cloud.githubusercontent.com/assets/5666297/13961273/48148014-f032-11e5-8a7c-42000623e7db.png)

-  Add Catalog # after Part # on selection grid below
![image](https://cloud.githubusercontent.com/assets/5666297/13961319/7a5873f0-f032-11e5-8ff4-5e4527787d71.png)

- Change underlining query ADD union with part catalog table. Only part catalog for supplier selected on the PO Details should show up for selection:
barcode show from catalog table (inv_part_catalogues_wv)
part number show from part table
catalog number show from catalog table
description show from catalog table.
group based on join from part table.

**Comment by giovanicani** [comment]
Add column on report to also show catalog # beside each part, if any.

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
The Catalog # is now displayed at the parts grid at Edit PO form. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/14014137/80c008ce-f1d2-11e5-96a0-552d33b24e7c.png)

Work in progress on adding it on Add form and also on parts modal. Query will be changed once it gets done

Done at report:

![image](https://cloud.githubusercontent.com/assets/13255706/14015161/e367f292-f1d8-11e5-92b1-c2aea6647931.png)

**Comment by d3sqa** [comment]
Currently, the catalog # is populating against the supplier.

Work in progress on:
- Data mapping from catalog table
- Populating only the specific parts for selection against the supplier

**Comment by giovanicani** [comment]
Kindly update ticket with query for us to review together. Also add table on UAT to test query.

**Comment by d3sqa** [comment]
Table has been created on UAT for testing and test data is also inserted

Following query retrieves all active parts from INV_PARTS with addition from catalog table against a supplier

```sql
SELECT * FROM 
       ( SELECT ROW_NUMBER() OVER
        (ORDER BY t.PAR_ID DESC ) rnum, 
        Count(*) over() as TotalRow ,
        t.*,
        (SELECT P.CATALOGUE_NUMBER FROM INV_PART_CATALOGUES_WV P WHERE P.PAR_ID=T.PAR_ID AND ROWNUM=1
        AND P.VEN_ID=5099)CATALOG_NUMBER,
        (SELECT P.CATALOGUE_DESCRIPTION FROM INV_PART_CATALOGUES_WV P WHERE P.PAR_ID=T.PAR_ID AND ROWNUM=1
        AND P.VEN_ID=5099)CATALOGUE_DESCRIPTION,
        (SELECT P.BARCODE_NUMBER FROM INV_PART_CATALOGUES_WV P WHERE P.PAR_ID=T.PAR_ID AND ROWNUM=1
        AND P.VEN_ID=5099)CATALOG_BARCODE_NUMBER
        FROM VIEW_INV_PARTS_DETAIL T) 
         WHERE
        rnum BETWEEN   1 AND 25


Following is the query which retrieves only the parts having catalog # against a supplier:

```sql
SELECT * FROM 
    ( SELECT ROW_NUMBER() OVER
     (ORDER BY PD.PAR_ID DESC ) rnum, 
     Count(*) over() as TotalRow ,
     PD.*,
     PC.CATALOGUE_NUMBER,
     PC.BARCODE_NUMBER AS CATALOG_BARCODE,
     PC.CATALOGUE_DESCRIPTION
     FROM VIEW_INV_PARTS_DETAIL PD 
     LEFT JOIN INV_PART_CATALOGUES_WV PC ON PC.PAR_ID=PD.PAR_ID WHERE PC.VEN_ID = 5259 )
     WHERE
     rnum BETWEEN   1 AND 25

**Comment by giovanicani** [comment]
This is the correct query that must be used

- Search barcode should search on parts and catalogue barcode fields
- Search by description should search on parts and catalogue description fields
- Have you created a catalogue number on the po details table (INV_PURCHASE_ORDER_DETAILS) ? You will need to.

```sql
SELECT par.barcode_number, par.code trailcon_part_number, NULL catalogue_number, par.description, pargro.description
FROM inv_parts_wv par 
LEFT JOIN inv_part_groups pargro ON par.pargro_id = pargro.pargro_id
WHERE par.active_flag = 'Y'
UNION
SELECT parcat.barcode_number, par.code trailcon_part_number, parcat.catalogue_number, parcat.catalogue_description, pargro.description
FROM inv_part_catalogues_wv parcat JOIN inv_parts_wv par ON parcat.par_id = par.par_id
LEFT JOIN inv_part_groups pargro ON par.pargro_id = pargro.pargro_id
WHERE par.active_flag = 'Y' AND parcat.ven_id = :VENDOR_HEADER;
```

**Comment by d3sqa** [comment]
Work in pogress

**Comment by d3sqa** [comment]
The catalog column has been added to the part's modal at PO screen.
The catalog # will be displayed when a particular supplier is selected along with other parts.

Correct data mapping as per written above has also been done

Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/14167776/09cb0b00-f737-11e5-915f-f32167dba350.png)

Ready to test in development environment

**Comment by giovanicani** [comment]
This is not working

Part #: R16129, see below:
![image](https://cloud.githubusercontent.com/assets/5666297/14285951/5c43f06c-fb1b-11e5-9de9-c1350d5541f0.png)

Why supplier catalog information not available on PO ? Same vendor was used. It should have 2 lines one without catalog and the other with the catalog info.
![image](https://cloud.githubusercontent.com/assets/5666297/14285979/7aad767c-fb1b-11e5-94ee-1b886bf41b32.png)

**Comment by d3sqa** [comment]
Done. Please see screenshots below:

![image](https://cloud.githubusercontent.com/assets/13255706/14341175/aa220268-fca8-11e5-9234-5b7fb8220f1e.png)

![image](https://cloud.githubusercontent.com/assets/13255706/14341177/b1ec1272-fca8-11e5-9939-d7e237ffd94d.png)

Ready to test in development environment

**Comment by d3sqa** [comment]
@giovanicani, is it possible to add both the parts at a time i.e. adding the part with catalog first and then adding the one without catalog ?

or should we apply restriction here ? Because whenever same part is added, the catalog reflects in both parts as the PAR_ID is same. Please see example below:

![image](https://cloud.githubusercontent.com/assets/13255706/14482954/9ce8bf58-015b-11e6-95c0-344c68bd8028.png)

**Comment by giovanicani** [comment]
@d3sqa no validation is required. I don't believe they would ever do this in the real world, however at this point, no validation is required.

The po listing should not show repeated catalog on this scenario. Can you check if the developer did what I asked 15 days ago ? If they did that then it should not repeat. Let me know if you have questions on this one. Thanks!
![image](https://cloud.githubusercontent.com/assets/5666297/14493336/eae35334-0152-11e6-97fd-56d59aadbb94.png)

**Comment by d3sqa** [comment]
Yes got the idea. The above point is now incorporated and the catalog # is not repeating now. Ready to test

**Comment by giovanicani** [comment]
resolved.
