### ISSUE TITLE
Cloud: Parts: Assign VMRS Fields on parts detail screen

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#64]
See tables below in red.

1. Only show active records on the selection box. Search by code or description on all 3 drop down list
2. pm_vmrs_system_asy_comp_vw is a new table:
```sql
[audit & ten_id fields]
vmrsysasycom_id - PK NOT NULL
vmrsysass_id - FK(pm_vmrs_system_assemblies) NOT NULL
code VARCHAR2(25) NOT NULL
description VARCHAR2(250) NOT NULL
active_flag VARCHAR2(1) DEFAULT 'Y' NOT NULL
notes VARCHAR2(1000)

add unique key (ten_id, vmrsysass_id, code)
```

![image](https://cloud.githubusercontent.com/assets/5666297/13963033/13f53d3e-f03a-11e5-9c94-279a9ff58bdc.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
@giovanicani, we are using adm_vmrs_system_asy_comp_vw as discussed earlier. The m_vmrs are no longer used.
Should we proceed with the ones you have mentioned or with the adm_vmrs ones ?

**Comment by giovanicani** [comment]
as discussed on the call please use the ones on the screen shot.

will have to drop ad_vmrs_system%%% tables, as we found out that using a new set of tables will cause issues on the integration with EMDECS.

**Comment by d3ssupport** [comment]
Work in Progress!

**Comment by giovanicani** [comment]
almost completed. still WIP

**Comment by d3sqa** [comment]
Data is now being saved and retrieved at the VMRS fields. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/14248044/cdc208e0-fa8b-11e5-8a9e-3c7ce5259819.png)

Ready to test in development environment

We will work on the VMRS setup screen to set the VMRS data

**Comment by giovanicani** [comment]
1. When I enter REMOVE on the assembly box, it doesnt bring any value.
2. When I enter 000 on the assembly box, it brings me all 000, it should only return the ones based on the selected reefer.

Sequence is: First select SYSTEM, then on ASSEMBLY only show ASSEMBLIES for that SYSTEM, then on COMPONENT, only show COMPONENTS for the selected ASSEMBLY

```
Hierarchy & Example:

SYSTEM - 013 - Brakes
        ASSEMBLY - 000 Brakes
                COMPONENT - 000 - Brakes
        ASSEMBLY - 001 Front Brakes & Drum
                COMPONENT - 001 - Backing Plate - Front Brake
                COMPONENT - 002 - Hardware, Mounting - Front Brake Backing Plate
                etc....
        ASSEMBLY - 002 Rear Brakes & Drum
                COMPONENT - 001 - Lever - Pedal & Sector Assembly, Parking Brake
                COMPONENT - 002 - Hardware, Mounting - Parking Brake Pedal & Sector Assembly Lever
                etc....
        ASSEMBLY - 003 Parking Brakes
                COMPONENT - 001 - Lever - Pedal & Sector Assembly, Parking Brake
                COMPONENT - 002 - Hardware, Mounting - Parking Brake Pedal & Sector Assembly Lever
                COMPONENT - 003 - Pad - Parking Brake Pedal
                etc....
        ASSEMBLY - 004 Spring Parking Brake (Separate Or Combination W/Service Brake)
        etc...
SYSTEM - 016 - Suspension
etc...
```


![image](https://cloud.githubusercontent.com/assets/5666297/14251500/5c60da8a-fa51-11e5-8732-7e99d257ed85.png)

**Comment by d3sqa** [comment]
Done. Please see screenshots below:

![image](https://cloud.githubusercontent.com/assets/13255706/14308077/21fae8de-fbed-11e5-9eb3-e12513e367fc.png)

![image](https://cloud.githubusercontent.com/assets/13255706/14308872/75237ba2-fbf2-11e5-92c5-ca2c36c19b7e.png)

The data is now dependent. System > Assembly > Component
When invalid data is entered, it will not be saved in the text field

Ready to test in development environment

**Comment by giovanicani** [comment]
skylook down. unable to test.

**Comment by d3sqa** [comment]
Please test now. Skylook in up

**Comment by giovanicani** [comment]
resolved.
