### ISSUE TITLE
Add PO Missing Finalize PO Check box

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#65]
Need to be able to finalize. Finalize will save and finalize PO.

![image](https://cloud.githubusercontent.com/assets/5666297/14027483/3b71083a-f1ce-11e5-9cdd-0020932e33de.png)

**Comment by giovanicani** [comment]
Also, Assign RO does not work if not saved. At least show message, please save PO in order to assign RO.

**Comment by d3sqa** [comment]
On Add PO, when the 'Finalized PO' checkbox is checked, the form will be saved and PO will be created as well as finalized. All the fields will be disabled in this case

![image](https://cloud.githubusercontent.com/assets/13255706/14072277/1bd3ca78-f4d8-11e5-9b00-742aeaa450b4.png)

Assign RO button has been disabled at the Add PO form

Ready to test in development environment

**Comment by giovanicani** [comment]
resolved.
