### ISSUE TITLE
Change Override by Branch to Override by Inventory

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#66]
Change id on table to be inventory
Change tab verbiage to say inventory
Change first column to be inventory selection not branch
Change button to say: Add Override, instead of Add Supplier.
![image](https://cloud.githubusercontent.com/assets/5666297/14094370/9f774f9e-f523-11e5-804d-9a5ec38756ce.png)

**Comment by d3sqa** [comment]
@giovanicani, which id needs be changed ? LOC_ID ?

![image](https://cloud.githubusercontent.com/assets/13255706/14098028/22728112-f591-11e5-95d1-39debdd366ca.png)

**Comment by giovanicani** [comment]
Yes. With war id

--
Giovani Cani

**Comment by d3sqa** [comment]
The renaming of labels has been done. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/14104722/17767708-f5c0-11e5-8852-b0b7eb23a978.png)

Work in progress on changing id

**Comment by d3sqa** [comment]
The Inventories has been mapped to the Inventory column. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/14168584/8d9b7e74-f73c-11e5-8738-85b889036f60.png)

Ready to test in development environment

**Comment by giovanicani** [comment]
ok thanks.
