### ISSUE TITLE
Cloud: Part Screen - On Hand checkbox change label

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#7]
Change label to say: Allow negative On Hand, instead of only "On Hand"

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Label has been changed to 'Allow negative On Hand'. Please see attached screenshot;

![screenshot_684](https://cloud.githubusercontent.com/assets/13255706/12383371/1b85f570-bdc7-11e5-9b85-cd325de6f13f.png)

Ready for testing in development environment.

**Comment by giovanicani** [comment]
Note that I will only test when the entire screen is ready. 

Functions: INSERT and UPDATE
and 
All Fields are functional.

Looking forward to the status update this coming Friday January 22nd.

Thanks!

**Comment by giovanicani** [comment]
however this issue has been fixed, so the ticket will be closed.
