### ISSUE TITLE
Cloud: Transfer Screen : Add parts not working

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#70]
1. As seen on the meeting, add parts does not work consistently.
2. Please change **order qty** to **transfer qty**
3. Button is missing
4. Please perform test of the entire screen, including barcode.

![image](https://cloud.githubusercontent.com/assets/5666297/14174906/8f96b832-f715-11e5-9928-eddab6ec65fe.png)

**Comment by d3sqa** [comment]
This issue occurred due to uncleared cache.
Now we are clearing the cache programmatically.

Ready to test in development environment

**Comment by giovanicani** [comment]
very good job! Works.
