### ISSUE TITLE
Cloud: Transfer : Auto Generate Transfer List

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#71]
Continuation from ticket #29 

![image](https://cloud.githubusercontent.com/assets/5666297/14174995/303928ba-f716-11e5-8e2e-762d3f96c09b.png)

**Comment by giovanicani** [comment]
Development Complete, Testing in progress as per meeting today.

**Comment by giovanicani** [comment]
please provide update.

**Comment by d3sqa** [comment]
It has been working whenever any one of the radio button is on along with 'Allow negative onhand' checked. But do we need 'Allow negative onhand' here as the -ve qty no longer stands in transfer ? Please provide feedback

**Comment by giovanicani** [comment]
You can remove allow negative onhand checkbox.

**Comment by d3sqa** [comment]
The Negative Onhand checkbox has been removed.
The list is generated successfully. Ready to test in development environment

**Comment by giovanicani** [comment]
okay, please make the generate list button disabled for now. Need to get more info from users on how this should work. Thanks.

**Comment by d3sqa** [comment]
The Generate List at the Transfer screen has been disabled now. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/14844343/2ce9d2a8-0c70-11e6-8523-2651514dbf4b.png)

**Comment by giovanicani** [comment]
thanks!
