### ISSUE TITLE
Cloud: Branches screen not finalized

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#72]
1. Need to increase width of the screen.
2. Province before country, city after postal code.

![image](https://cloud.githubusercontent.com/assets/5666297/14213190/a73e1e18-f804-11e5-9706-13fc055133d9.png)

3. Warehouse should say Inventory.

![image](https://cloud.githubusercontent.com/assets/5666297/14213177/939d15ee-f804-11e5-9aa2-8ed1339b3990.png)

4. Cannot add remove AR Taxes
5. Cannot add remove AP Taxes

**Comment by d3sqa** [comment]
Work in progress

**Comment by giovanicani** [comment]
please provide update.

**Comment by d3sqa** [comment]
Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/14457738/21c30d8c-00c6-11e6-97f2-554b3d4ce3e8.png)

![image](https://cloud.githubusercontent.com/assets/13255706/14457742/2c3cee04-00c6-11e6-97ef-d8ac1ddaf33f.png)

![image](https://cloud.githubusercontent.com/assets/13255706/14457748/3b6d5b98-00c6-11e6-869a-83880b0a827b.png)

![image](https://cloud.githubusercontent.com/assets/13255706/14457749/3e80ebe2-00c6-11e6-8141-f168131aa31d.png)


Few tweaks regarding mandatory data needs to be done, we are working on it. We will update you on the latest status by the end of day

**Comment by giovanicani** [comment]
thanks!

**Comment by d3sqa** [comment]
Done with the functionality. Ready to test in development environment

**Comment by giovanicani** [comment]
@d3sqa why am I getting this error after changing the description of the branch ? Screen should be able to save without tax information.

![image](https://cloud.githubusercontent.com/assets/5666297/14796771/09ec6b40-0afd-11e6-853d-32aa65888104.png)

Where can I delete the tax record ? If a tax is not being used (no FK violation) it should allow to remove the tax record. In the example below I added 2 lines by mistake and want to remove one, how do I do to remove?
![image](https://cloud.githubusercontent.com/assets/5666297/14796839/6c09a4f0-0afd-11e6-9719-4916b2f6f25c.png)

**Comment by d3sqa** [comment]
Mandatory checks has been removed from the A/R Taxes and A/P Taxes tabs. However, if the user enters any of the field within these tabs, then validation will stand

Deletion functionality has also been incorporated on both Add and Edit forms. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/14848674/41519c86-0c88-11e6-901d-f2c81576f9ac.png)

Ready to test in development environment

**Comment by giovanicani** [comment]
thanks!
