### ISSUE TITLE
Cloud: Inventory Screen not finalized

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#73]
1. Increase width of the screen to look better
2. Add border
3. Put country after province / state, city after postal code.
4. Add field type, drop down with: MOBILE, CONTAINER, MAIN
5. Add latitude and longitude auto populated based on address when user leaves address, city, postal code fields.
6. Remove associated facilities tab
7. Add drop down list to change branch that the inventory is associated with

![image](https://cloud.githubusercontent.com/assets/5666297/14213404/cae29082-f805-11e5-9d4b-0871280b364e.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Above points has been incorporated. Please see screenshots below:

Add Inventory:

![image](https://cloud.githubusercontent.com/assets/13255706/14344176/85d3789e-fcbf-11e5-83ce-4ecf6f1968da.png)

Edit Inventory:

![image](https://cloud.githubusercontent.com/assets/13255706/14344200/b04429de-fcbf-11e5-84c7-99965e04a071.png)

Whenever the inventory becomes inactive, that inventory will not show up anywhere in the inventory fields

**Comment by giovanicani** [comment]
Need work on lat and long when the address is updated. right now is not working. If address does not exist then lat and long should be null (blank) and NOT 0

**Also, make branch mandatory field on the screen.**

**Comment by d3sqa** [comment]
Branch field has been made mandatory
Invalid address issue is now resolved. The coordinates will remain blank in case of an invalid address.
If a google map API returns coordinates, only then will they be displayed on the form

The coordinates will be displayed on the base of the following:

Address
City
Postal Code
Country

Ready to test in development environment

**Comment by giovanicani** [comment]
@d3sqa Where are all the other branches ?

![image](https://cloud.githubusercontent.com/assets/5666297/14797140/1ca69dda-0aff-11e6-9116-ed562a7b89cf.png)


list of branches below ...
![image](https://cloud.githubusercontent.com/assets/5666297/14797186/605c476e-0aff-11e6-9ca3-4e06393ed62e.png)

**Comment by d3sqa** [comment]
The Branches has been mapped. Some UI related tweaks are remaining, We are working on it. Also, the working on displaying branches on description as currently it picks up code to display results

**Comment by d3sqa** [comment]
All the branches having Active Flag = Y are now reflect at the branch drop down. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/14847272/206ef95c-0c81-11e6-8f29-529c93e28c8a.png)

**Comment by giovanicani** [comment]
thanks works.
