### ISSUE TITLE
Cloud: Transfer Details - not consistent

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#75]
Sequence of columns not consistent with other screens:

1. Core should come after description.

![image](https://cloud.githubusercontent.com/assets/5666297/14227131/c7a5d474-f8c3-11e5-9f3e-535e4851c319.png)

**Comment by d3sqa** [comment]
Done. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/14239423/f90c9240-fa54-11e5-8609-2a551833482b.png)

Ready to test in development environment

**Comment by giovanicani** [comment]
resolved.
