### ISSUE TITLE
Cloud: Parts screen - Change Supercedes to Superseded by

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#76]
Please change label from "Supersedes" to "Superseded by".

![image](https://cloud.githubusercontent.com/assets/5666297/14253031/e63fdc32-fa57-11e5-9abe-5de32fdbccfa.png)

When pressing the SAVE button on a part that has value on the Superseded By box, then show warning message, with an OK button:

**Please note that this part has been superseded by [Superseded by part #] - [Superseded by part description]. It is recommended to zero inventory and deactivate superseded parts.** 

**[OK]**

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Done. Message is now prompted in case a superseded part is added while creating or updating part's information. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/14272962/672cebc8-fb20-11e5-83b7-f66d29b2692c.png)

@giovanicani , do we need to implement the functionality as well i.e. when the user updates the inventory to 0 or deactivate the superseded part and then comes back to saving the actual part, the warning message will not be displayed in this case?

**Comment by giovanicani** [comment]
As discussed need to always show message if Superseded By is not null. Remember the XP and Windows 10 example:

Part XP: Has been superseded by Windows 10.

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Done as per discussion. Ready to test in development environment

**Comment by giovanicani** [comment]
skylook down. unable to test.

**Comment by giovanicani** [comment]
resolved.
