### ISSUE TITLE
Cloud - Parts Screen: Cannot inactivate parts with OH <> 0

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#77]
When a part is being saved, please check if onhand on **ALL Inventories** is **ZERO**

If OH is different than zero, show ERROR message on saving:

**Cannot Save Changes
Part is in stock in one or more inventories, it cannot be deactivated. Only parts with ZERO on-hand can be de-activated. Please check the Stock Availability tab for more details.**

**[OK]**

Make sure that ONHAND function is used for checking OH.

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
The message is now prompted when the user un checks the Active checkbox.
Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/14273394/ca45c510-fb23-11e5-80f2-9e240c37677a.png)

Ready to test in development environment

**Comment by giovanicani** [comment]
works. thanks!
