### ISSUE TITLE
Cloud: Receiving Details - Change verbiage

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#78]
Change verbiage below to:

**Negotiated Total Cost (excluding taxes and other fees)**

![image](https://cloud.githubusercontent.com/assets/5666297/14258554/de6e1960-fa70-11e5-93c0-28b104b69c1b.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Verbiage has been renamed. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/14271264/9dc2214a-fb10-11e5-9c98-2cc9695e8b2f.png)

Ready to test in development environment

**Comment by giovanicani** [comment]
done! thanks!
