### ISSUE TITLE
Cloud: Receiving Details - Need to add conversion column

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#79]
We forgot to add the conversion column on receiving.

![image](https://cloud.githubusercontent.com/assets/5666297/14259126/7400a75c-fa73-11e5-9815-17302abb61a8.png)

- After Ordering UOM, add column: "UOM Conv.", default value 1 (or the value on the parts details assuming that the order and stock UOM of the Receiving match the parts details screen). **Inline updateable**

*Please use QTY_CONVERSION from INV_INVENTORY_RCV_DETAILS_WV*. Need to rename QTDY_CONVERSION to QTY_CONVERSION - remove D
- After new column UOM Conv, add: "Stock Effect. Qty", which will be a ready only formula:

**Stock Effect. Qty = Qty x UOM Conv**

- Change verbiage: Ordering UOM to Order UOM and Stocking UOM to Stock UOM, this will help save some space

Example: If PO is a ordering UOM is BOXOF12 but STOCKING UOM is EACH, then it would look like this:

```
Part: 99999
Desc: Oil Spray
Qty: 1
Order UOM: BOXOF12
UOM Conv.: 12
Stock Effect. Qty: 12    (formula)
Stock UOM: EA
``` 

When finalizing receiving perform the following validation:

1. All lines must have conversion, and it cannot be zero.
2. If Ordering UOM is different than Stock UOM, AND Conversion is 1, then show warning: The following part(s) xxx,yyyy,zzzz have different order and stock UOM however conversion is 1, proceed with finalize process ? [Proceed] [Cancel]

If Cancel then, cancel process and user needs to fix conversion and finalize again.

After finalized inv_inventory_audits.unit_cost for part will be "Total Cost" divided by "Stock Effect. Qty"

**Comment by giovanicani** [comment]
looks good, needs the following tweaks:

1. Divide the cost by effective quantity when storing on inv_inventory_audits
2. UOM Conv same as parts detail if order and stock UOM of the Receiving match the parts details screen

**Comment by d3sqa** [comment]
Done. Ready to test in development environment

**Comment by giovanicani** [comment]
skylook down. unable to test.

**Comment by giovanicani** [comment]
seems to be working, thanks!
