### ISSUE TITLE
Cloud: Create table for parts supplier catalog

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#8]
This is a new feature and a table currently does not exists, suggested name:

inv_part_catalogues (inv_part_catalogues_wv)
[audit fields & PK]
ten_id - NUMBER - not null
ven_id - NUMBER - not null
par_id - NUMBER - not null
catalogue_number - VARCHAR2(50) - not null
catalogue_desc - VARCHAR2(100) - not null
catalogue_cost - NUMBER(10,4)

Please remove UOM and Stock UOM from the tab screen. Not needed

![image](https://cloud.githubusercontent.com/assets/5666297/12202889/19097544-b5fa-11e5-9261-42765a356dce.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Table namely INV_PART_CATALOGUES has been created. Please find the screenshot below:

![partscatalogue](https://cloud.githubusercontent.com/assets/13255706/12214939/0baa8b98-b6c9-11e5-9763-0818dca91af7.png)

UOM and Stock UOM has been removed from Supplier Catalog tab. See below screenshot:

![image](https://cloud.githubusercontent.com/assets/13255706/12215060/be7c6ddc-b6cd-11e5-8ee1-83a168ddd52e.png)

**Comment by giovanicani** [comment]
okay
