### ISSUE TITLE
Cloud UOM - When adding new UOM, active should be checked by default

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#80]
This is part of the standard and should be applied to all screens.

![image](https://cloud.githubusercontent.com/assets/5666297/14280282/e6a51900-faff-11e5-9c0f-f9d245706ed4.png)

**Comment by d3sqa** [comment]
While adding a new UOM, the active flag is checked by default
Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/14348130/f7a78e4c-fcd3-11e5-8b94-600bbf82be34.png)

Ready to test in development environment

**Comment by giovanicani** [comment]
works.
