### ISSUE TITLE
Cloud: Adding a new UOM does not show up on parts detail

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#81]
Need to make sure that when adding / changing UOM on UOM Admin screen, it should appear on the parts listing.

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Newly added UOM are now successfully reflecting at the Stocking/Re-ordering UOM drop down. When saved, the value is updated against the part
When UOM is updated at the UOM screen, the updated value starts to show up on part detail UOM drop downs

Ready to test in development environment

**Comment by giovanicani** [comment]
okaya thanks.
