### ISSUE TITLE
Cloud: If NOT FINALIZED Need to be able to VOID PO / Receiving / Transfer / Physical Count

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#82]
If NOT FINALIZED Need to be able to VOID PO / Receiving / Transfer / Physical Count.

- Void only makes sense on the UPDATE Form. Buttons, OK and Cancel. Cancel unchecks the void flag.
- When user clicks on VOID flag needs to popup a window for user to enter void notes **(void_date and notes already exist on the database, just please make sure it is VARCHAR2(2000) and not CLOB)**.

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Void functionality has been incorporated on PO, Receiving, Transfer and Physical Count screen. Notes field type has also been changed to VARCHAR(2000)

Ready to test in development environment

**Comment by giovanicani** [comment]
okay.
