### ISSUE TITLE
Cloud: PO Details Close button should Close tab if no changes to the data

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#83]
PO Details Close button should close browser tab if no changes to data.

If changes to data should show current warning.

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
The tab will be closed when there are no changes. When there is some change, a warning will be displayed.
Done on PO, Receiving, Transfer and Physical Count

Ready to test in development environment

**Comment by giovanicani** [comment]
skylook down. unable to test.

**Comment by giovanicani** [comment]
resolved.
