### ISSUE TITLE
Cloud: PO and Receiving - Provide Dev Team with the correct query for Last Cost

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#84]
Provide Dev Team with the correct query for Last Cost

**Comment by giovanicani** [comment]
@d3sqa 
Team, last cost will be based on the latest cost for that part for the supplier on the PO / Receiving.

Last cost is a read only column, and will have the numbers formated, example: 8,432.11

Any other question on this, please let me know.

**Comment by d3sqa** [comment]
@giovanicani, which should be given priority ? PO or Receiving ? i.e. from which module will the latest last cost be picked against a particular part ?

**Comment by giovanicani** [comment]
@d3sqa this is the query they should be using, it should go to the receiving and find last cost for this vendor and part.

Let me know if any questions.

```sql
SELECT invrcvdet.cost last_cost
FROM inv_inventory_rcv_details invrcvdet 
JOIN inv_inventory_receivings invrec ON invrcvdet.invrec_id = invrec.invrec_id
WHERE invrec.receiving_date < NVL(:screen_receiving_date,systimestamp)
AND par_id = :screen_par_id
AND ven_id = :screen_ven_id;
```

**Comment by d3sqa** [comment]
Thanks @giovanicani. We will incorporate this query

**Comment by d3sqa** [comment]
Done at Receiving screen. Work in progress on Purchase Order screen

**Comment by d3sqa** [comment]
Last cost has been incorporated in the purchase order screen as well. Ready to test in development environment

**Comment by giovanicani** [comment]
okay.
