### ISSUE TITLE
Cloud: Onhand calculation Instructions

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#85]
This ticket will explain a few scenarios on how to calculate OH.

![image](https://cloud.githubusercontent.com/assets/5666297/14357768/0546ce1c-fcb8-11e5-90fb-247295b102c5.png)

**Comment by giovanicani** [comment]
Today is April 7 at 11:00:00 AM, what is my current onhand ?

![image](https://cloud.githubusercontent.com/assets/5666297/14357817/382bbdc4-fcb8-11e5-9125-a843cc126776.png)

OH on April 7 at 11:00:00 AM = 5 - 2 + 1 -1 + 2 - 3 = 2

**Comment by giovanicani** [comment]
What is my onhand as of **March 7 at 10:19:00AM** ?

![image](https://cloud.githubusercontent.com/assets/5666297/14360598/3161cbe8-fcc5-11e5-9514-455e24aa846f.png)

Finds latest PC that took place before or on **March 7 at 10:19:00AM**
Once found, start counting until transaction date is less or equal to **March 7 at 10:19:00AM**

**March 7 at 10:19:00AM** OH = 10 - 1 + 2 - 3 - 6 + 2 = 4

**Comment by d3sqa** [comment]
We have verified the onhand excluding the RO and Adj as we will work on these two.
The onhand is correct if RCV, TRANS and PC is taken into consideration.

We have one question regarding it, will ask in a meeting today

**Comment by giovanicani** [comment]
thanks!

**Comment by giovanicani** [comment]
As of Date on PC needs to be lock down. User cannot change, this has been requested by Trailcon.

**Comment by d3sqa** [comment]
PC Finalized As Of date field has now been made read only to avoid back dating the PC. Ready to test in development environment

**Comment by giovanicani** [comment]
activities related to this have been completed.
