### ISSUE TITLE
Cloud: Create Adjustment Screen

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#86]
Needs to work similarly to the transfer

- Adjustment will do an adjustment of a part(s) quantity(ies) in the same inventory, example adjusting quantity from 10 to 8;
- After finalized adjustment will insert a record for each part adjusted in the inv_inventory_audits_wv;
- Cost to be populated from the get part cost function; 
- Unit Cost and Total Cost Read only;
- Core column not required;
- Does not need to create part, just add part from parts list
- Adjustment As Of Date not updateable. Set as the date and time when creating adjustment. Use this date and time when inserting into inv_inventory_audits_wv.

![image](https://cloud.githubusercontent.com/assets/5666297/14364413/ca686b10-fcd6-11e5-9e04-cd35821d64d2.png)

Adjustment Listing
![image](https://cloud.githubusercontent.com/assets/5666297/14364843/aa7d98e6-fcd8-11e5-9cdf-56e67af7f876.png)

**Comment by giovanicani** [comment]
Tables:
```sql
desc INV_INVENTORY_ADJUSTMENTS_WV;
drop CUS_ID
drop LAST_INSERT_USERNAME
drop LAST_UPDATE_USERNAME
drop LAST_INSERT_DATE
check audit triggers

desc INV_INVENTORY_ADJ_DETAILS_WV;
check audit triggers
```

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Update:

Listing screen has been designed. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/14457450/f511921a-00c3-11e6-8692-2eac851d9f84.png)

Detail screen has also been designed. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/14457464/0c7fe6cc-00c4-11e6-840a-23fac9a1ec27.png)

We are working at detail form's fields, void and finalized

**Comment by giovanicani** [comment]
thanks!

**Comment by d3sqa** [comment]
Adjustment screen has been implemented completely. Ready to test in development environment

**Comment by giovanicani** [comment]
it works.
