### ISSUE TITLE
Cloud - PC ON Hand multiple locations, how to handle when they are in separated PC #'s

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#88]
Cloud - PC ON Hand multiple locations, how to handle when they are in separated PC #'s

**Comment by giovanicani** [comment]
Please apply filter to the first set location fields. Filter will ignore 2 set of location fields.

Please add a note on the generate parts list popup: "Filter is applied only to primary part location fields."

**Comment by d3sqa** [comment]
Filter has been applied to the first set of data against a part. Verbiage has also been added. Ready to test in development environment

**Comment by giovanicani** [comment]
thanks.
