### ISSUE TITLE
Cloud: Create Unit Reading Screen (grid)

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#89]
Screen will be admin and based on the rep_unit_readings_wv view.

- When user clicks on the RTMI ID or WO ID, it should open the RTMI or RO in another tab.
- User is able to add new readings (RTMI and WO will be null in these cases):
a. Miles or KM allowed if ym_units_wv.reefer_flag = N;
b. Ontime, Runtime or Eletric Hours allowed if ym_units_wv.reefer_flag = Y;
c. User will be able to void a reading, if voided reading is not longer considered for billing (void_flag)
d. Giovani will create a trigger on the table that cannot accept lower readings if day is more recent that previous date, except if there is a reading reset.

A reset is required when a hubodometer changes.

```
Example of grid below:

On L# 3, the hubodometer broke and a new one had to be installed. Which was done on RO2. 
Note that only after a reset, the reading could be lower again. Reset usually means that a new hubo was installed. 
Same rule applies to the 3 reefer readings.

L# Unit #  Preferred # RO# RTMI#  Reading Date       Reading  UOM   Reset At   Reset At UOM   Reset To   Reset To UOM
1  123456  P123456     RO3        Apr 15 03:00:10PM      260  KM 
2  123456  P123456                Apr 13 08:00:50AM       60  KM
3  123456  P123456     RO2        Apr 12 02:59:50PM                    1,600           KM          1           KM
4  123456  P123456     RO1        Apr 11 09:19:23AM    1,500  KM
5  123456  P123456          RT1   Apr 10 10:00:00AM    1,000  KM              
```
Require filters:
-- Unit #
-- Preferred #
-- Date Range
-- RO #
-- RTMI #

Hubo picture:
![image](https://cloud.githubusercontent.com/assets/5666297/14527915/d7f1819c-021a-11e6-991a-392144977da4.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by giovanicani** [comment]
please provide update.

**Comment by d3sqa** [comment]
Grid has been done. Please check in development environment

![image](https://cloud.githubusercontent.com/assets/13255706/14636194/7b31fe1e-0643-11e6-80d8-2ab78c23875e.png)

**Comment by giovanicani** [comment]
Line number not required.

**Comment by giovanicani** [comment]
ETA is 21 of April

**Comment by d3sqa** [comment]
Update:

1. The Addition for reefer readings (ym_units_wv.reefer_flag = Y) has been done
2. Some tweaks are left with addition of hubo reading  ym_units_wv.reefer_flag = Y
3. Tweaks regarding success messages and void are remaining

We are working on it

**Comment by giovanicani** [comment]
please provide update.

**Comment by d3sqa** [comment]
Unit Readings screen has been implemented. 

- Add/Update feature has been completed
- The above logic based on reefer_flag = Y/N has been incorporated
- Void functionality is working
- Filter is working fine

Ready to test in development environment

**Comment by giovanicani** [comment]
- Please show date and time on the reading date column
- Please show date and time field after unit # (screen below), default should be current date and time
- At the bottom, have 3 buttons: Save & Add Another, Save & Close, Close
- Ontime, Runtime and Electrical hours should not have the mandatory field. At least one is mandatory.
- Notes field should be always visible after Electric Reading. **Notes is not void notes. Please make screen adjustments**
- Reading cannot be updated only voided
- See if you can show the records with thousands separator, example: 99,123. ***All numeric fields must be aligned to the right. This is part of our standard I dont understand why this is still not happening.***



![image](https://cloud.githubusercontent.com/assets/5666297/14798674/c5cb2e06-0b06-11e6-8e66-44d3f7c3793c.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Update:

- Date and time is now displayed at the listing. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/14813852/1b9ea3d8-0bbd-11e6-81a7-7a7886f97d76.png)

- Please show date and time field after unit # (screen below), default should be current date and time

![image](https://cloud.githubusercontent.com/assets/13255706/14813869/2ee0e24e-0bbd-11e6-9267-cbf7c931d90f.png)

- Mandatory check has been removed such that only one reading is required has been implemented

- Notes field is displayed after electrical reading and the notes are now displayed at the listing in the notes column

![image](https://cloud.githubusercontent.com/assets/13255706/14813973/9ed75a24-0bbd-11e6-91b0-c168d005f140.png)

- Numeric field has been right aligned at the listing

![image](https://cloud.githubusercontent.com/assets/13255706/14813997/c009c9a2-0bbd-11e6-9fe1-a084ab44ce6f.png)

- Void upon double click has been done

Work in progress on:

- To remove * from the form against these readings
- At the bottom, have 3 buttons: Save & Add Another, Save & Close, Close
- Masking on the reading to be provided in the form as well

**Comment by giovanicani** [comment]
@d3sqa 

- Search on the Grid is not working
- Please add a void column (last) Y / N to indicate whether or not the record has been voided.
- **Double click is not a standard to VOID**. Need to leave it how it was before, double click open popup and allow used to click void and save.

**Comment by d3sqa** [comment]
Following points have been incorporated:

1. At the bottom, have 3 buttons: Save & Add Another, Save & Close, Close
2. Masking on the reading to be provided in the form as well
3. Filter has been working and the Search has been made read only
4. Void column has been added to the listing
5. Void functionality has been incorporated as done previously. The user can now void and re-open the window in which all the fields will be disabled

Ready to test in development environment

**Comment by giovanicani** [comment]
okay, please remove the quick search bar if it is not functional.

Leaving it there will confuse the user. thanks!

**Comment by d3sqa** [comment]
The Quick Search has been removed from the Readings screen. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/14882566/d804b076-0d52-11e6-8ecd-00e3dd04dacb.png)
