### ISSUE TITLE
Cloud: Create table for preferred supplier by branch

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#9]
Table does not exist: suggested table:

inv_vendor_branches (inv_vendor_branches)
[audit fields & PK]
ten_id - NUMBER - not null
ven_id - NUMBER - not null
loc_id - NUMBER - not null
start_date - TIMESTAMP WITH TIMEZONE
end_date - TIMESTAMP WITH TIMEZONE 

Remove Active column on the tab screen

![image](https://cloud.githubusercontent.com/assets/5666297/12203043/ee16d2fe-b5fa-11e5-9a70-5692f0f3100d.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Table named INV_VENDOR_BRANCHES has been created. Please see the screenshot below:

![img_09012016_115512](https://cloud.githubusercontent.com/assets/13255706/12214908/18e55a28-b6c8-11e5-84d3-f99807454c40.png)

Active column has been removed. Please see attached screenshot:

![image](https://cloud.githubusercontent.com/assets/13255706/12215067/ea7a870c-b6cd-11e5-884d-af03dd9ff8b1.png)

**Comment by giovanicani** [comment]
okay.
