### ISSUE TITLE
Cloud: Safety Certificate Maintenance Screen

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#90]
- Based on view: rla_safety_certificates_wv

- Grid Read Only Columns:
-- Owner
-- Unit #
-- Preferred #
-- Certificate Letter
-- Certificate Number
-- Certificate Day / Month / Year
-- RO # associated to that safety, link opens in a new tab RO# details.
-- Notes

- Sort by most recent create_date record first.

- Grid Filters
-- Cert. Letter
-- Cert. Number
-- Unit #
-- Preferred #
-- RO #

- User can add or delete certificates. Delete requires confirmation.
- Validations on add function:
-- Certificate Letter can have max 2 characters;
-- Certificate Date cannot be older than 1 year from current date system date;
-- Certificate Date cannot be more than 1 year in the future from current system date;
-- Certificate Letter + Certificate Number must be unique per uni_id record;

- On table / view do the following
-- Change notes from CLOB to varchar2(2000);
-- Drop LAST_INSERT_USERNAME, LAST_UPDATE_USERNAME, LAST_INSERT_DATE
-- Adjust audit trigger to keep the standard (context variable)
-- Add FK and Index worord_id

**Comment by d3sqa** [comment]
Work in progress

**Comment by giovanicani** [comment]
please provide update.

**Comment by d3sqa** [comment]
Update:

Safety Certificate screen has been implemented. Please see screenshots below:

![image](https://cloud.githubusercontent.com/assets/13255706/14636514/607fbdfc-0645-11e6-866a-b9365e05282f.png)

![image](https://cloud.githubusercontent.com/assets/13255706/14636522/66535130-0645-11e6-8a26-6ef089ac5e9d.png)

Edit form has also been done. However due to some reason, the month is not reflecting. We will update this ticket by day end

**Comment by giovanicani** [comment]
Can you also make sure that Letter is always uppercase.
And column Headings as per standard have only the first letter in capital.

**Comment by giovanicani** [comment]
ETA is 21 of April

**Comment by d3sqa** [comment]
The certificate letter is now in uppercase. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/14669638/215f8d5a-0703-11e6-9590-8e859248b3aa.png)

![image](https://cloud.githubusercontent.com/assets/13255706/14669647/2bc9321e-0703-11e6-89fb-f7fad1dae61c.png)

Ready to test in development environment

@giovanicani, the column headings are in capital letters through out our application. Do you want us to change it ?

**Comment by giovanicani** [comment]
@d3sqa yes, would like to change, we can do this slowly as we touch the screens again to do tweaks. My focus right now is functionality.

On the Add Certificate, can you please add a box before month for Day ? By default will be 1, but user can change. Suggestion is that when save you do a to_date(date provided) if the to_date failed, it means that the day informed is incorrect example: Feb 31 2016. Oracle's TO_DATE function is a good way to validate, unless PHP / .Net has a better one.

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
The day field has been incorporated and checks have been implemented on it. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/14704295/5b3d3e30-07cd-11e6-9d3f-440d9fcdc675.png)

Ready to test in development environment

**Comment by giovanicani** [comment]
Works, but can you change the button label as per below:

Cancel change to Close.

**Comment by d3sqa** [comment]
Button has been renamed to Close on both the Add and Update forms. Please see screenshots below:

![image](https://cloud.githubusercontent.com/assets/13255706/14807533/d2d739c4-0b96-11e6-80d7-a0a21218ded8.png)

![image](https://cloud.githubusercontent.com/assets/13255706/14807558/f506e63e-0b96-11e6-8fe4-fd3f19c0d17d.png)

Ready to test in development environment

**Comment by giovanicani** [comment]
works. thanks
