### ISSUE TITLE
Cloud: MRO Link - EMDECS API - Merge Logic

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#91]
As discussed these are the scenarios involving linked ROs and merging into original RO in order to send to EMDECS.

All merging must be done on the API side. I hope this makes sense, let me know if you have any questions.

![image](https://cloud.githubusercontent.com/assets/5666297/14533118/d7905e96-0231-11e6-9066-811fdf260c9a.png)

**Comment by giovanicani** [comment]
linked to #93

**Comment by d3sqa** [comment]
@giovanicani, new application updates are available at UAT. The statuses has been set based on the above logic. 'WAITING ON LINKED ROS' status has been incorporated. You can verify it

However, there are few audit log tweaks which we are doing right now. We are also testing the XML. Will get back with the updated status of XML and audit Log

**Comment by giovanicani** [comment]
Great Team! Thanks for the update.

On Wed, Apr 20, 2016 at 8:05 AM, d3sqa <notifications@github.com> wrote:

> @giovanicani <https://github.com/giovanicani>, new application updates
> are available at UAT. The statuses has been set based on the above logic.
> 'WAITING ON LINKED ROS' status has been incorporated. You can verify it
>
> However, there are few audit log tweaks which we are doing right now. We
> are also testing the XML. Will get back with the updated status of XML and
> audit Log
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/GCSO2/D3S-INVENTORY/issues/91#issuecomment-212398612>
>



-- 
Giovani Cani
Project Manager (PMP, CSM & OCP)
Software Delivery Services

**Comment by d3sqa** [comment]
The audit log tweaks have been done and the xml test has been done. The above logic has been incorporated and is ready to be tested in UAT Environment

**Comment by giovanicani** [comment]
okay!
