### ISSUE TITLE
Cloud: Auto Create PO function

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#92]
Associated to #19.

![image](https://cloud.githubusercontent.com/assets/5666297/14526826/15f38294-0214-11e6-9c01-b718e3ed0202.png)

**Comment by giovanicani** [comment]
Testing currently in progress.

**Comment by giovanicani** [comment]
please provide update.

**Comment by d3sqa** [comment]
Done. Ready to test in development environment

**Comment by giovanicani** [comment]
@d3sqa how did you test this function ? I don't seem to make it work.

Report shows no part and Create PO(s) button does nothing.


Please change button labels to:
(add number 1 and 2 in front)

1 - Re-Order Report
2 - Create PO(s)

**Comment by d3sqa** [comment]
@giovanicani, following criteria regarding a part should meet in order to auto create PO:

1. Part should have been present on the audit table (Inventory inquiry screen) i.e. a transaction against the part should be present
2. Part should have onhand = 0
3. Part should have an override or preferred supplier
4. Date range should cover the part transaction date
5. When onhand is less than MIN quantity

Work is in progress on report

Question: If onhand is 0, then while creating a PO, should we order 1 by default ? 
Also, we have restricted negative values currently. Should we handle the negative values as well ?

**Comment by giovanicani** [comment]
Why part should have ONHAND = 0 ? Where this criteria came from ?

If user selects MIN / MAX, then you need to order so that the quantity hits MAX or more. For example:

Part ABC, Inventory 123 
Min:10 each 
Max 20 each, 
Current OH = 5 each

System should suggest to purchase 15 each more, so that it hits 20.

If for the same part, the current onhand is 12, the it will not be picked up by the report and procedure, as 12 is higher than the minimum.

**Comment by d3sqa** [comment]
@giovanicani, if the Onhand is less than 0, then the PO will be created. In case the On hand is 0, still there is a need to created a PO to restock the item. 
What should be done in case of a 0 onhand ? Should the PO not generate in this case ?

The scenario of MIN/MAX has been tested and is working fine. For 1st scenario, we use:
Part #: P9977
Inventory: M66
PO: PO001535

For the 2nd scenario:
Part #: P9977
Inventory: M44
PO was not created in this case

**Comment by giovanicani** [comment]
Usage Method = look into the inventory audits table and see all parts used* for that period of time selected make sure that you convert to the timezone of the user and truncate the date so that time is irrelevant

*used = Used on a RO or Transferred Out of the inventory.

Please add note on the popup box at the bottom that says the following:

Usage Method only takes into consideration parts issued on a RO or Transferred Out.

**Comment by d3sqa** [comment]
@giovanicani, while creating auto POs via the usage, should we give priority to 'Override Supplier' and then to 'Preferred Supplier' or should we simply use 'Preferred Supplier'

![image](https://cloud.githubusercontent.com/assets/13255706/15073531/6b6ec6a6-13b3-11e6-8f3c-00c0742112c4.png)

Please provide your feedback on this

**Comment by giovanicani** [comment]
Yes, if part has an override supplier for that inventory, please consider the override supplier, not the preferred supplier. 

If there are no override supplier, for part and inventory, then use preferred supplier.

**Comment by d3sqa** [comment]
Work in progress on the supplier logic which needs to be done from the procedure end. Also working on the data being displayed on the report

**Comment by d3sqa** [comment]
Supplier logic has been implemented. First priority will be given to override supplier and then to Preferred supplier
Testing is in progress for data validation on the report

Please find attached screenshot of report:

![image](https://cloud.githubusercontent.com/assets/13255706/15143907/88af831c-16c5-11e6-8574-daabc7dc8c5d.png)

**Comment by d3sqa** [comment]
Report data has been validated. Report is ready to be tested against both usage and Min/Max
Auto POs have also been successfully created

Ready to test in development environment

**Comment by giovanicani** [comment]
okay
