### ISSUE TITLE
Cloud: MRO Link (SRT vs non-SRT) - Change specification

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#93]
As discussed document specs attached.

[ProposedChanges-SRTvsMiscROsv.1.0.pdf](https://github.com/GCSO2/D3S-INVENTORY/files/219377/ProposedChanges-SRTvsMiscROsv.1.0.pdf)

**Comment by giovanicani** [comment]
.1. Please change the layout to show RO number at the top left corner. Make it big font as represented below:

![image](https://cloud.githubusercontent.com/assets/5666297/14709395/65b29aba-079e-11e6-8dc3-20ba1ba3dc8e.png)

.2. Before creating a linked RO. Validate that ...

- ... Customer is entered;
- ... Location is entered;
- ... Readings are entered (including Reefer if unit has a reefer);
- ... At least one labour line is entered;

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Following validations have been applied while creating a linked RO:

- Customer is entered
- Location is entered
- Readings are entered (including Reefer if unit has a reefer)
- At least one labour line is entered

The font size has been made bigger. However we will remove the parenthesis from it. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/14784232/eaed7836-0b0d-11e6-9d2a-c03d51494eb5.png)

Application updates are now available at UAT

**Comment by giovanicani** [comment]
Found a bug when selecting a labour line with 0.25, as per screen shot below, it shows ZERO on the grid.

![image](https://cloud.githubusercontent.com/assets/5666297/14785786/6adecc82-0aca-11e6-936e-90c3027f75c3.png)

**Comment by giovanicani** [comment]
Please change the linked reference
![image](https://cloud.githubusercontent.com/assets/5666297/14786128/72e41490-0acb-11e6-8e02-c7a01f74e695.png)

Make it something similar to the line below

![image](https://cloud.githubusercontent.com/assets/5666297/14786240/f6d51e3e-0acb-11e6-91d8-93bbb3ee358d.png)

**Comment by giovanicani** [comment]
Hi @d3sqa, can you make sure the 2 items above are done for tomorrow? The team is working on the training material and I would like to give them a few screen shots.

@d3sqa can you also provide me with a list of outstanding items for this change ? Need to update management.

Much appreciated.
Giovani

**Comment by d3sqa** [comment]
@giovanicani, Yes sure, we are working on it right now and will update this ticket today

Following items are pending to be done:
1. Parent RO's checklist should go to EMDECS. Needs to include its content in the XML
2. PM Safety labour should not be added if there are already Misc labours added to the RO

We are working on these items as well. Will update when we are done with it

**Comment by d3sqa** [comment]
The format of the heading has been changed. Please see below screenshot:

![image](https://cloud.githubusercontent.com/assets/13255706/14810308/b30ba1e2-0bab-11e6-9e3a-19dc71319148.png)

The labour hrs rounding of to 0 issues has also been fixed. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/14810381/1f3eb598-0bac-11e6-9ef4-321b9ed6e087.png)

'PM Safety labour should not be added if there are already Misc labours added to the RO' has also been done

Updates for the above mentioned fixes has been available in UAT environment

**Comment by giovanicani** [comment]
Thanks. Validated the fixes mentioned above.

**Comment by d3sqa** [comment]
Checklist has been done but testing is pending because db link for test EMDECS is not working. Please check the db link for EMDECS in UAT

**Comment by giovanicani** [comment]
ok will talk about this tomorrow at the meeting.

**Comment by tufailzafar** [comment]
SELECT *
FROM   e$mb_pm_checklist_defs

**Comment by giovanicani** [comment]
Giovani to work with Erik to make this db link active again.

**Comment by giovanicani** [comment]
This has been resolved as per email sent from Erik. Can you please test and let me know ?

**Comment by d3sqa** [comment]
Checklist has been done and tested for the following scenarios:

1. When parent and linked RO both have checklist, the Parent's checklist should go to EMDECS
2. When parent has a checklist and the linked RO hasn't

**Comment by giovanicani** [comment]
resolved.
