### ISSUE TITLE
Cloud: Inventory Inquiry show unit cost instead of total cost

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#94]
On the inventory inquiry screen we should always show the unit cost of the part, not the total cost.

Need to use the function to get cost from part at the time of the transaction and insert into the audit table.

**Also please change the heading on the inventory inquiry to Unit Cost, instead of Cost.**

Thanks!

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Done. Now Unit Cost will be displayed in the inventory inquiry screen against the Adjustment and Receiving. Please see screenshot below for label renamed:

![image](https://cloud.githubusercontent.com/assets/13255706/14671171/d197d87a-0709-11e6-839f-66c4bb1ac986.png)

Ready to test in development environment

**Comment by giovanicani** [comment]
thanks.

**Comment by giovanicani** [comment]
done.
