### ISSUE TITLE
Cloud - Inventory Transfer Report: Adjustments

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#95]
linked to #29 

Please do the following tweaks on the Inventory Adjustment Report

- Remove Core Column
- Remove Unit Cost and Total Cost
- Add part location from the From inventory (so that employee can find the physical part)
- Add barcode after Part#
- After UOM add a column with header Revised, and a line so that user can write the revised quantity.
- Make every other line with gray background as example below
- Add Total number of lines (parts) at the bottom.

![img_8738](https://cloud.githubusercontent.com/assets/5666297/14645389/7a216a70-0623-11e6-8910-072e7f137a7b.JPG)

![img_8739](https://cloud.githubusercontent.com/assets/5666297/14645405/8296c498-0623-11e6-84e7-e7faf7900049.JPG)

**Comment by d3sqa** [comment]
Adjustments have been done to the transfer report. Please find the screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/14673768/4fe28e3c-0719-11e6-94a5-36efd8497df2.png)

Currently, we are displaying only the room in the Location column. Should we concatenate Rack with it as well ? Please provide feedback

**Comment by giovanicani** [comment]
@d3sqa yes, rack and bin also.

On the barcode column, I need the actual image of the barcode (with bars) and not the number/letters.

Looking good... thanks!

**Comment by d3sqa** [comment]
Thanks for the feedback
Work in progress

**Comment by d3sqa** [comment]
Rack and Bin has been displayed along with the room using space as a separator. Also, the barcodes are now displayed in the bar format. Please see the report's screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/14699550/2147d156-07b2-11e6-8b33-d1c4bd776c99.png)

Ready to test in development environment

**Comment by giovanicani** [comment]
users love it! Thanks

Just move the Total # of Parts to the Left (since this is not a total of quantity), and call it:

5 Different Parts Number(s)

**Comment by d3sqa** [comment]
Tweak has been done. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/14732615/c730cd84-0875-11e6-892f-ce1d8d78ec3d.png)

@giovanicani, same part can be added multiple times within the transfer. And the new verbiage says 'Different Parts Number(s)'. So should we just count the repeated part just once in this case? Please provide your feedback

**Comment by giovanicani** [comment]
Got it. Let's make it. 

There are XX line items.

This is more generic. Thanks.

**Comment by d3sqa** [comment]
Verbiage has been changed. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/14774940/dccbc228-0ad4-11e6-8ad9-5cde431d1448.png)

Ready to test in development environment

**Comment by giovanicani** [comment]
thanks!
