### ISSUE TITLE
Cloud: VMRS Screen

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-INVENTORY#99]
- Move the 3 add buttons on the panel below to save space
- How can I delete a record ? If record is being used, and user tries to delete record, like everywhere else in the system it should let the user know, and only allow deactivation.
- Add a popup on the VMRS Assemblies grid to assign job types. See table script below.

![image](https://cloud.githubusercontent.com/assets/5666297/14797403/ad65a0ea-0b00-11e6-8136-f0b7630a6e65.png)

```sql

CREATE TABLE pm_vmrs_sys_asy_job_types(create_date        TIMESTAMP WITH TIME ZONE NOT NULL
,create_user         VARCHAR2(30) NOT NULL
,last_update_date    TIMESTAMP WITH TIME ZONE
,last_update_user    VARCHAR2(30)
,ten_id              NUMBER NOT NULL
,vmrsysasyjobtyp_id  NUMBER NOT NULL)
TABLESPACE TCS_01_TS;
/

ALTER TABLE pm_vmrs_sys_asy_job_types ADD (vmrsysass_id NUMBER NOT NULL);
ALTER TABLE pm_vmrs_sys_asy_job_types ADD (jobtyp_id NUMBER NOT NULL);
/

ALTER TABLE pm_vmrs_sys_asy_job_types ADD CONSTRAINT vmrsysasyjobtyp_pk PRIMARY KEY (vmrsysasyjobtyp_id);
ALTER TABLE pm_vmrs_sys_asy_job_types ADD CONSTRAINT vmrsysasyjobtyp_sysasyjt_uk UNIQUE(vmrsysass_id, jobtyp_id);
ALTER TABLE pm_vmrs_sys_asy_job_types ADD CONSTRAINT vmrsysasyjobtyp_ten_fk FOREIGN KEY(ten_id) REFERENCES sys_tenants(ten_id);
ALTER TABLE pm_vmrs_sys_asy_job_types ADD CONSTRAINT vmrsysasyjobtyp_jobtyp_fk FOREIGN KEY(jobtyp_id) REFERENCES adm_job_types(jobtyp_id);
ALTER TABLE pm_vmrs_sys_asy_job_types ADD CONSTRAINT vmrsysasyjobtyp_vmrsysass_fk FOREIGN KEY(vmrsysass_id) REFERENCES pm_vmrs_system_assemblies(vmrsysass_id);
/

CREATE OR REPLACE TRIGGER pm_vmrs_sys_asy_job_types_briu
BEFORE INSERT OR UPDATE ON pm_vmrs_sys_asy_job_types
FOR EACH ROW
BEGIN
   IF inserting THEN
      IF :new.vmrsysasyjobtyp_id IS NULL THEN
         :new.vmrsysasyjobtyp_id := oraseq.nextval;
      END IF;
      :new.create_date := systimestamp;
      :new.create_user := NVL(system_functions_pkg.get_context_value('user_user_name'),user);
      IF :new.ten_id is null THEN
         :new.ten_id := system_functions_pkg.get_ten_id_from_context();
      END IF;
   ELSE
      :new.last_update_date := systimestamp;
      :new.last_update_user := NVL(system_functions_pkg.get_context_value('user_user_name'),user);
   END IF;
END pm_vmrs_sys_asy_job_types_briu;
/

CREATE OR REPLACE VIEW pm_vmrs_sys_asy_job_types_wv AS
SELECT create_date
      ,create_user
      ,last_update_date
      ,last_update_user
      ,ten_id
      ,vmrsysasyjobtyp_id
      ,vmrsysass_id
      ,jobtyp_id
 FROM pm_vmrs_sys_asy_job_types;
/

GRANT select, update, insert, delete ON tcs_owner.pm_vmrs_sys_asy_job_types_wv TO tcs_default_role;
CREATE OR REPLACE PUBLIC SYNONYM pm_vmrs_sys_asy_job_types_wv FOR tcs_owner.pm_vmrs_sys_asy_job_types_wv;
/
```

VMRS Assembly should look like this. Associate job type will allow user to select job types associated to that assembly record.
![image](https://cloud.githubusercontent.com/assets/5666297/14797832/9e3fe8e4-0b02-11e6-98d0-634f14fb0b8a.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Above requirements are incorporated. Please see screenshots below:

![image](https://cloud.githubusercontent.com/assets/13255706/14849244/5bbf886e-0c8b-11e6-81a6-5af45dad282a.png)

![image](https://cloud.githubusercontent.com/assets/13255706/14849258/60fa78d4-0c8b-11e6-9597-11d8e64c35c5.png)

The buttons namely 'Add VMRS System', 'Add VMRS Assembly' and 'Add VMRS Component' have been moved to the panel

![image](https://cloud.githubusercontent.com/assets/13255706/14849278/82d259f4-0c8b-11e6-96a2-2d15f0759e8d.png)

![image](https://cloud.githubusercontent.com/assets/13255706/14849282/89784728-0c8b-11e6-8691-350013244cbe.png)

![image](https://cloud.githubusercontent.com/assets/13255706/14849284/8ef9c208-0c8b-11e6-9ea3-7a10c5f6f54b.png)

Ready to test in development environment

**Comment by giovanicani** [comment]
good. seems to work... but how do I de-associate a job type ?

Perhaps instead of SAVE, have a button that says Associate Job Type and another that says De-Associate Job Type.

**Comment by d3sqa** [comment]
Work in progress on de-associate feature

**Comment by d3sqa** [comment]
De-associating Job Type from the assembly has been incorporate. Please see screenshots below:

![image](https://cloud.githubusercontent.com/assets/13255706/14883673/c7edea12-0d58-11e6-8750-1ae5bd76f000.png)

![image](https://cloud.githubusercontent.com/assets/13255706/14883675/d07de2cc-0d58-11e6-8255-a875216d1463.png)

**Comment by giovanicani** [comment]
okay
